# FILE: arabic_data.py

ARABIC_DATA = {

    "7th_grade": {
        "lesson_1": {
            "words": [
                {"arabic": "اَلسَّلامُ عَلَیکُم", "farsi": "سلام بر شما", "english": "Peace be upon you",
                 "english_pronunciation": "As-salam-u alay-kum"},
                {"arabic": "وَعَلَیکُمُ السَّلام", "farsi": "و بر شما سلام", "english": "And upon you be peace",
                 "english_pronunciation": "Wa alay-kum as-salam"},
                {"arabic": "کَیفَ حالُکَ؟", "farsi": "حالت چطور است؟ (مذکر)", "english": "How are you? (masculine)",
                 "english_pronunciation": "Kay-fa ha-lu-ka?"},
                {"arabic": "کَیفَ حالُکِ؟", "farsi": "حالت چطور است؟ (مؤنث)", "english": "How are you? (feminine)",
                 "english_pronunciation": "Kay-fa ha-lu-ki?"},
                {"arabic": "أَنا بِخَیرٍ، شُکراً", "farsi": "من خوبم، ممنون", "english": "I am fine, thank you",
                 "english_pronunciation": "Ana bi-khair, shuk-ran"},
                {"arabic": "صَباحُ الخَیرِ", "farsi": "صبح بخیر", "english": "Good morning",
                 "english_pronunciation": "Sa-bah-ul Khair"},
                {"arabic": "مَساءُ الخَیرِ", "farsi": "عصر بخیر", "english": "Good evening",
                 "english_pronunciation": "Masa-ul Khair"},
                {"arabic": "تِلمیذ", "farsi": "دانش‌آموز (پسر)", "english": "Student (male)",
                 "english_pronunciation": "Til-meez"},
                {"arabic": "تِلمیذَة", "farsi": "دانش‌آموز (دختر)", "english": "Student (female)",
                 "english_pronunciation": "Til-mee-za"},
                {"arabic": "أُستاذ", "farsi": "استاد / معلم (مرد)", "english": "Teacher (male)",
                 "english_pronunciation": "Us-tadh"},
                {"arabic": "مُعَلِّمَة", "farsi": "معلم (زن)", "english": "Teacher (female)",
                 "english_pronunciation": "Mu-'al-li-ma"},
                {"arabic": "مَدرَسَة", "farsi": "مدرسه", "english": "School", "english_pronunciation": "Mad-ra-sa"},
                {"arabic": "قاعَة", "farsi": "تالار / کلاس", "english": "Classroom", "english_pronunciation": "Qaa-'a"},
                {"arabic": "مَکتَب", "farsi": "میز تحریر", "english": "Desk", "english_pronunciation": "Mak-tab"},
                {"arabic": "کُرَّاسَة", "farsi": "دفتر", "english": "Notebook", "english_pronunciation": "Kur-ra-sa"},
                {"arabic": "مِمحاة", "farsi": "پاک‌کن", "english": "Eraser", "english_pronunciation": "Mim-ha"},
                {"arabic": "حَقِیبَة", "farsi": "کیف", "english": "Bag", "english_pronunciation": "Ha-kee-ba"},
                {"arabic": "مِقلَمَة", "farsi": "جامدادی", "english": "Pencil case",
                 "english_pronunciation": "Miq-la-ma"},
                {"arabic": "کَرَّاسَة", "farsi": "دفتر مشق", "english": "Exercise book",
                 "english_pronunciation": "Kar-ra-sa"},
                {"arabic": "سَبُّورَة", "farsi": "تخته سیاه", "english": "Blackboard",
                 "english_pronunciation": "Sab-boo-ra"},
            ],
            "sentences": [
                {"arabic": "أَنتَ طَبیبٌ ماهِرٌ.", "farsi": "تو پزشک ماهری هستی.",
                 "english": "You are a skilled doctor.", "english_pronunciation": "Anta tabibun mahirun."},
                {"arabic": "هِیَ مُهَندِسَةٌ نَشیطَةٌ.", "farsi": "او مهندسی کوشا است.",
                 "english": "She is an active engineer.", "english_pronunciation": "Hiya muhandisatun nashitatun."},
                {"arabic": "أَنا تِلمیذٌ فِی الصَّفِّ السابِعِ.", "farsi": "من دانش‌آموزی در کلاس هفتم هستم.",
                 "english": "I am a student in the seventh grade.",
                 "english_pronunciation": "Ana tilmeezun fis-saffis-sabi'"},
                {"arabic": "هَل هَذِهِ مَدرَسَةٌ جَدِیدَةٌ؟", "farsi": "آیا این مدرسه جدید است؟",
                 "english": "Is this a new school?", "english_pronunciation": "Hal hadhihi madrasatun jadeedatun?"},
                {"arabic": "الأُستاذُ فِی القاعَةِ.", "farsi": "استاد در کلاس است.",
                 "english": "The teacher is in the classroom.", "english_pronunciation": "Al-ustadhu fil-qaa'ati."},
                {"arabic": "التِّلمیذَةُ تَکتُبُ فِی الکُرَّاسَةِ.", "farsi": "دانش‌آموز (دختر) در دفتر می‌نویسد.",
                 "english": "The student (female) is writing in the notebook.",
                 "english_pronunciation": "At-tilmeezatu taktubu fil-kurrasati."},
                {"arabic": "الحَقِیبَةُ عَلى المَکتَبِ.", "farsi": "کیف روی میز است.",
                 "english": "The bag is on the desk.", "english_pronunciation": "Al-haqeebatu ala al-maktabi."},
                {"arabic": "المِقلَمَةُ فِی الحَقِیبَةِ.", "farsi": "جامدادی در کیف است.",
                 "english": "The pencil case is in the bag.", "english_pronunciation": "Al-miq-lamatu fil-haqeeba."},
                {"arabic": "السَّبُّورَةُ فِی القاعَةِ نَظِیفَةٌ.", "farsi": "تخته سیاه در کلاس تمیز است.",
                 "english": "The blackboard in the classroom is clean.",
                 "english_pronunciation": "As-sabbooratu fil-qaa'ati nazeefatun."},
                {"arabic": "أَکتُبُ فِی الکَرَّاسَةِ بِالمِمحاةِ.", "farsi": "در دفتر مشق با پاک‌کن می‌نویسم.",
                 "english": "I write in the exercise book with the eraser.",
                 "english_pronunciation": "Aktubu fil-karraasati bil-mimha."},
            ]
        },
        "lesson_2": {
            "words": [
                {"arabic": "هٰذَا", "farsi": "این (مذکر)", "english": "This (masculine)",
                 "english_pronunciation": "Ha-dha"},
                {"arabic": "هٰذِهِ", "farsi": "این (مؤنث)", "english": "This (feminine)",
                 "english_pronunciation": "Ha-dhi-hi"},
                {"arabic": "ذٰلِکَ", "farsi": "آن (مذکر)", "english": "That (masculine)",
                 "english_pronunciation": "Dha-lika"},
                {"arabic": "تِلکَ", "farsi": "آن (مؤنث)", "english": "That (feminine)",
                 "english_pronunciation": "Til-ka"},
                {"arabic": "شَجَرَة", "farsi": "درخت", "english": "Tree", "english_pronunciation": "Sha-ja-ra"},
                {"arabic": "کِتاب", "farsi": "کتاب", "english": "Book", "english_pronunciation": "Ki-tab"},
                {"arabic": "سَیّارَة", "farsi": "ماشین", "english": "Car", "english_pronunciation": "Say-ya-ra"},
                {"arabic": "قَلَم", "farsi": "قلم", "english": "Pen", "english_pronunciation": "Qa-lam"},
                {"arabic": "بَیت", "farsi": "خانه", "english": "House", "english_pronunciation": "Bayt"},
                {"arabic": "باب", "farsi": "در", "english": "Door", "english_pronunciation": "Baab"},
                {"arabic": "نافِذَة", "farsi": "پنجره", "english": "Window", "english_pronunciation": "Naa-fi-dha"},
                {"arabic": "حَدِیقَة", "farsi": "باغ", "english": "Garden", "english_pronunciation": "Ha-dee-qa"},
                {"arabic": "زَهرَة", "farsi": "گل", "english": "Flower", "english_pronunciation": "Zah-ra"},
                {"arabic": "مِیز", "farsi": "میز", "english": "Table", "english_pronunciation": "Meez"},
                {"arabic": "کُرسِیّ", "farsi": "صندلی", "english": "Chair", "english_pronunciation": "Kur-si"},
                {"arabic": "حائِط", "farsi": "دیوار", "english": "Wall", "english_pronunciation": "Haa'it"},
                {"arabic": "أَرضِیَّة", "farsi": "کف / زمین", "english": "Floor", "english_pronunciation": "Ar-diy-ya"},
            ],
            "sentences": [
                {"arabic": "هَل هٰذَا کِتابٌ؟ نَعَم، هٰذَا کِتابٌ.", "farsi": "آیا این کتاب است؟ بله، این کتاب است.",
                 "english": "Is this a book? Yes, this is a book.",
                 "english_pronunciation": "Hal hadha kitabun? Na'am, hadha kitabun."},
                {"arabic": "تِلکَ السَّیّارَةُ جَمیلَةٌ.", "farsi": "آن ماشین زیبا است.",
                 "english": "That car is beautiful.", "english_pronunciation": "Tilka as-sayyaratu jameelatun."},
                {"arabic": "هٰذِهِ شَجَرَةٌ کَبِیرَةٌ.", "farsi": "این درخت بزرگ است.",
                 "english": "This is a big tree.", "english_pronunciation": "Hadhihi shajaratun kabeeratun."},
                {"arabic": "ذٰلِکَ البَیتُ قَدِیمٌ.", "farsi": "آن خانه قدیمی است.", "english": "That house is old.",
                 "english_pronunciation": "Dhalika al-baytu qadeemun."},
                {"arabic": "النَّافِذَةُ فِی الحَدِیقَةِ مَفتُوحَةٌ.", "farsi": "پنجره در باغ باز است.",
                 "english": "The window in the garden is open.",
                 "english_pronunciation": "An-naafidhatu fil-hadeeqati maftoohatun."},
                {"arabic": "هٰذِهِ زَهرَةٌ جَمیلَةٌ.", "farsi": "این گل زیبا است.",
                 "english": "This is a beautiful flower.", "english_pronunciation": "Hadhihi zahratun jameelatun."},
                {"arabic": "الکِتابُ عَلى المِیزِ.", "farsi": "کتاب روی میز است.",
                 "english": "The book is on the table.", "english_pronunciation": "Al-kitabu ala al-meezi."},
                {"arabic": "الکُرسِیُّ بِجانِبِ الحائِطِ.", "farsi": "صندلی کنار دیوار است.",
                 "english": "The chair is next to the wall.",
                 "english_pronunciation": "Al-kursiyyu bi-jaanib al-haa'iti."},
                {"arabic": "الأَرضِیَّةُ نَظِیفَةٌ.", "farsi": "کف تمیز است.", "english": "The floor is clean.",
                 "english_pronunciation": "Al-ardiyyatu nazeefatun."},
            ]
        },
        "lesson_3": {
            "words": [
                {"arabic": "أَب", "farsi": "پدر", "english": "Father", "english_pronunciation": "Ab"},
                {"arabic": "أُم", "farsi": "مادر", "english": "Mother", "english_pronunciation": "Umm"},
                {"arabic": "أَخ", "farsi": "برادر", "english": "Brother", "english_pronunciation": "Akh"},
                {"arabic": "أُخت", "farsi": "خواهر", "english": "Sister", "english_pronunciation": "Ukht"},
                {"arabic": "جَد", "farsi": "پدربزرگ", "english": "Grandfather", "english_pronunciation": "Jadd"},
                {"arabic": "جَدَّة", "farsi": "مادربزرگ", "english": "Grandmother", "english_pronunciation": "Jadda"},
                {"arabic": "عائِلَة", "farsi": "خانواده", "english": "Family", "english_pronunciation": "Aa-ila"},
                {"arabic": "صَدِیق", "farsi": "دوست (مرد)", "english": "Friend (male)",
                 "english_pronunciation": "Sa-deeq"},
                {"arabic": "صَدِیقَة", "farsi": "دوست (زن)", "english": "Friend (female)",
                 "english_pronunciation": "Sa-dee-qa"},
                {"arabic": "جار", "farsi": "همسایه (مرد)", "english": "Neighbor (male)",
                 "english_pronunciation": "Jaar"},
                {"arabic": "جارَة", "farsi": "همسایه (زن)", "english": "Neighbor (female)",
                 "english_pronunciation": "Jaa-ra"},
                {"arabic": "أَبَوَین", "farsi": "والدین", "english": "Parents", "english_pronunciation": "Aba-wayn"},
                {"arabic": "اِبن", "farsi": "پسر", "english": "Son", "english_pronunciation": "Ibn"},
                {"arabic": "اِبنَة", "farsi": "دختر", "english": "Daughter", "english_pronunciation": "Ib-na"},
                {"arabic": "عَمّ", "farsi": "عمو", "english": "Uncle (paternal)", "english_pronunciation": "Amm"},
                {"arabic": "خال", "farsi": "دایی", "english": "Uncle (maternal)", "english_pronunciation": "Khaal"},
            ],
            "sentences": [
                {"arabic": "هٰذَا أَبِی.", "farsi": "این پدرم است.", "english": "This is my father.",
                 "english_pronunciation": "Hadha abee."},
                {"arabic": "أُمِّی فِی البَیتِ.", "farsi": "مادرم در خانه است.", "english": "My mother is at home.",
                 "english_pronunciation": "Ummi fil-bayti."},
                {"arabic": "أَخِی تِلمیذٌ.", "farsi": "برادرم دانش‌آموز است.", "english": "My brother is a student.",
                 "english_pronunciation": "Akhee tilmeezun."},
                {"arabic": "تِلکَ جَدَّتِی.", "farsi": "آن مادربزرگم است.", "english": "That is my grandmother.",
                 "english_pronunciation": "Tilka jaddatee."},
                {"arabic": "العائِلَةُ فِی الحَدِیقَةِ.", "farsi": "خانواده در باغ است.",
                 "english": "The family is in the garden.", "english_pronunciation": "Al-aa'ilatu fil-hadeeqati."},
                {"arabic": "الجارُ یَسكُنُ فِی البَیتِ الجَدِیدِ.", "farsi": "همسایه در خانه جدید زندگی می‌کند.",
                 "english": "The neighbor lives in the new house.",
                 "english_pronunciation": "Al-jaaru yaskunu fil-bayti al-jadeedi."},
                {"arabic": "الأَبَوَینِ یَعمَلانِ.", "farsi": "والدین کار می‌کنند.",
                 "english": "The parents are working.", "english_pronunciation": "Al-abawayni ya'malaani."},
                {"arabic": "الاِبنَةُ تَلعَبُ فِی الحَدِیقَةِ.", "farsi": "دختر در باغ بازی می‌کند.",
                 "english": "The daughter is playing in the garden.",
                 "english_pronunciation": "Al-ibnatu tal'abu fil-hadeeqati."},
                {"arabic": "العَمُّ یَزورُنا غَداً.", "farsi": "عمو فردا به دیدن ما می‌آید.",
                 "english": "The uncle visits us tomorrow.", "english_pronunciation": "Al-ammu yazooruna ghadan."},
            ]
        },
        "lesson_4": {
            "words": [
                {"arabic": "مَطبَخ", "farsi": "آشپزخانه", "english": "Kitchen", "english_pronunciation": "Mat-bakh"},
                {"arabic": "غُرفَة", "farsi": "اتاق", "english": "Room", "english_pronunciation": "Ghur-fa"},
                {"arabic": "سَرِیر", "farsi": "تخت", "english": "Bed", "english_pronunciation": "Sa-reer"},
                {"arabic": "مِرآة", "farsi": "آینه", "english": "Mirror", "english_pronunciation": "Mir-aat"},
                {"arabic": "خِزانَة", "farsi": "کمد", "english": "Wardrobe", "english_pronunciation": "Khi-za-na"},
                {"arabic": "مَغسَلَة", "farsi": "دستشویی", "english": "Sink", "english_pronunciation": "Magh-sa-la"},
                {"arabic": "ثَلّاجَة", "farsi": "یخچال", "english": "Refrigerator",
                 "english_pronunciation": "Thal-la-ja"},
                {"arabic": "فُرن", "farsi": "اجاق", "english": "Oven", "english_pronunciation": "Furn"},
                {"arabic": "مِکنَسَة", "farsi": "جارو", "english": "Broom", "english_pronunciation": "Mik-na-sa"},
                {"arabic": "سَجادَة", "farsi": "فرش", "english": "Carpet", "english_pronunciation": "Sajaada"},
                {"arabic": "مِصباح", "farsi": "چراغ", "english": "Lamp", "english_pronunciation": "Mis-baah"},
                {"arabic": "مُکَیِّف", "farsi": "کولر", "english": "Air conditioner",
                 "english_pronunciation": "Mu-kay-yif"},
                {"arabic": "حَمّام", "farsi": "حمام", "english": "Bathroom", "english_pronunciation": "Ham-maam"},
                {"arabic": "صالَة", "farsi": "سالن", "english": "Living room", "english_pronunciation": "Saa-la"},
                {"arabic": "مِفتاح", "farsi": "کلید", "english": "Key", "english_pronunciation": "Mif-taah"},
            ],
            "sentences": [
                {"arabic": "أُمِّی فِی المَطبَخِ.", "farsi": "مادرم در آشپزخانه است.",
                 "english": "My mother is in the kitchen.", "english_pronunciation": "Ummi fil-matbakhi."},
                {"arabic": "السَّرِیرُ فِی الغُرفَةِ.", "farsi": "تخت در اتاق است.",
                 "english": "The bed is in the room.", "english_pronunciation": "As-sareeru fil-ghurfati."},
                {"arabic": "المِرآةُ عَلى الحائِطِ.", "farsi": "آینه روی دیوار است.",
                 "english": "The mirror is on the wall.", "english_pronunciation": "Al-mir-aatu ala al-haa'iti."},
                {"arabic": "الثَّلّاجَةُ فِی المَطبَخِ جَدِیدَةٌ.", "farsi": "یخچال در آشپزخانه جدید است.",
                 "english": "The refrigerator in the kitchen is new.",
                 "english_pronunciation": "Ath-thallajatu fil-matbakhi jadeedatun."},
                {"arabic": "أَخِی یَستَخدِمُ المِکنَسَةَ.", "farsi": "برادرم از جارو استفاده می‌کند.",
                 "english": "My brother uses the broom.", "english_pronunciation": "Akhee yastakhdimu al-miknasata."},
                {"arabic": "السَّجادَةُ عَلى الأَرضِیَّةِ.", "farsi": "فرش روی کف است.",
                 "english": "The carpet is on the floor.", "english_pronunciation": "As-sajaadatu ala al-ardiyyati."},
                {"arabic": "المِصباحُ فِی الصالَةِ.", "farsi": "چراغ در سالن است.",
                 "english": "The lamp is in the living room.", "english_pronunciation": "Al-misbaahu fis-saalati."},
                {"arabic": "المُکَیِّفُ یَعمَلُ جَیِّداً.", "farsi": "کولر خوب کار می‌کند.",
                 "english": "The air conditioner works well.",
                 "english_pronunciation": "Al-mukayyifu ya'malu jayyidan."},
                {"arabic": "المِفتاحُ فِی الحَمّامِ.", "farsi": "کلید در حمام است.",
                 "english": "The key is in the bathroom.", "english_pronunciation": "Al-miftaahu fil-hammaami."},
            ]
        },
        "lesson_5": {
            "words": [
                {"arabic": "سُوق", "farsi": "بازار", "english": "Market", "english_pronunciation": "Sooq"},
                {"arabic": "دُکّان", "farsi": "مغازه", "english": "Shop", "english_pronunciation": "Duk-kaan"},
                {"arabic": "خُبز", "farsi": "نان", "english": "Bread", "english_pronunciation": "Khubz"},
                {"arabic": "لَحم", "farsi": "گوشت", "english": "Meat", "english_pronunciation": "Lahm"},
                {"arabic": "فاکِهَة", "farsi": "میوه", "english": "Fruit", "english_pronunciation": "Faa-ki-ha"},
                {"arabic": "خَضراء", "farsi": "سبزیجات", "english": "Vegetables", "english_pronunciation": "Khad-raa"},
                {"arabic": "مال", "farsi": "پول", "english": "Money", "english_pronunciation": "Maal"},
                {"arabic": "بائِع", "farsi": "فروشنده (مرد)", "english": "Seller (male)",
                 "english_pronunciation": "Baa-i'"},
                {"arabic": "بائِعَة", "farsi": "فروشنده (زن)", "english": "Seller (female)",
                 "english_pronunciation": "Baa-i'a"},
                {"arabic": "سِعر", "farsi": "قیمت", "english": "Price", "english_pronunciation": "Si'r"},
                {"arabic": "تُفّاح", "farsi": "سیب", "english": "Apple", "english_pronunciation": "Tuffaah"},
                {"arabic": "مَوز", "farsi": "موز", "english": "Banana", "english_pronunciation": "Mawz"},
                {"arabic": "جَزَر", "farsi": "هویج", "english": "Carrot", "english_pronunciation": "Jazar"},
                {"arabic": "بَطاطِس", "farsi": "سیب‌زمینی", "english": "Potato", "english_pronunciation": "Bataatis"},
                {"arabic": "مَحَفَّظَة", "farsi": "کیف پول", "english": "Wallet", "english_pronunciation": "Mah-fazza"},
            ],
            "sentences": [
                {"arabic": "أَذهَبُ إلى السُّوقِ.", "farsi": "به بازار می‌روم.", "english": "I go to the market.",
                 "english_pronunciation": "Adhhabu ila as-sooqi."},
                {"arabic": "البائِعُ فِی الدُّکّانِ.", "farsi": "فروشنده در مغازه است.",
                 "english": "The seller is in the shop.", "english_pronunciation": "Al-baa'i'u fid-dukkaani."},
                {"arabic": "أَشترِی خُبزاً ولَحماً.", "farsi": "نان و گوشت می‌خرم.", "english": "I buy bread and meat.",
                 "english_pronunciation": "Ashtaree khubzan wa lahman."},
                {"arabic": "الفاکِهَةُ فِی السُّوقِ طازَجَةٌ.", "farsi": "میوه در بازار تازه است.",
                 "english": "The fruit in the market is fresh.",
                 "english_pronunciation": "Al-faakihatu fis-sooqi taazajatun."},
                {"arabic": "أُمِّی تَشترِی خَضراءَ مِن البائِعَةِ.", "farsi": "مادرم از فروشنده (زن) سبزیجات می‌خرد.",
                 "english": "My mother buys vegetables from the seller (female).",
                 "english_pronunciation": "Ummi tashtaree khadraa'a min al-baa'i'ati."},
                {"arabic": "سِعرُ التُّفّاحِ بَسیطٌ.", "farsi": "قیمت سیب ارزان است.",
                 "english": "The price of the apple is cheap.", "english_pronunciation": "Si'ru at-tuffaahi baseetun."},
                {"arabic": "المَحَفَّظَةُ فِی جَیبی.", "farsi": "کیف پول در جیبم است.",
                 "english": "The wallet is in my pocket.", "english_pronunciation": "Al-mahfazzatu fi jaybee."},
                {"arabic": "أَشترِی مَوزاً وجَزَراً.", "farsi": "موز و هویج می‌خرم.",
                 "english": "I buy bananas and carrots.", "english_pronunciation": "Ashtaree mawzan wa jazaran."},
            ]
        },
        "lesson_6": {
            "words": [
                {"arabic": "مَدِینَة", "farsi": "شهر", "english": "City", "english_pronunciation": "Madeena"},
                {"arabic": "قَریَة", "farsi": "روستا", "english": "Village", "english_pronunciation": "Qarya"},
                {"arabic": "شارِع", "farsi": "خیابان", "english": "Street", "english_pronunciation": "Shaari'"},
                {"arabic": "مَیدان", "farsi": "میدان", "english": "Square", "english_pronunciation": "Maydaan"},
                {"arabic": "مَنزِل", "farsi": "خانه", "english": "Home", "english_pronunciation": "Manzil"},
                {"arabic": "مَسجِد", "farsi": "مسجد", "english": "Mosque", "english_pronunciation": "Masjid"},
                {"arabic": "مُستَشفى", "farsi": "بیمارستان", "english": "Hospital",
                 "english_pronunciation": "Mustashfa"},
                {"arabic": "صَیدَلِیَّة", "farsi": "داروخانه", "english": "Pharmacy",
                 "english_pronunciation": "Saydaliyya"},
                {"arabic": "مَکتَبَة", "farsi": "کتابخانه", "english": "Library", "english_pronunciation": "Maktaba"},
                {"arabic": "مَطعَم", "farsi": "رستوران", "english": "Restaurant", "english_pronunciation": "Mat'am"},
                {"arabic": "حَدِیقَة عُمومِیَّة", "farsi": "پارک عمومی", "english": "Public park",
                 "english_pronunciation": "Hadeeqa 'umoomiyya"},
                {"arabic": "مَحَطَّة", "farsi": "ایستگاه", "english": "Station", "english_pronunciation": "Mahatta"},
                {"arabic": "بَنک", "farsi": "بانک", "english": "Bank", "english_pronunciation": "Bank"},
                {"arabic": "مَکتب بَرید", "farsi": "اداره پست", "english": "Post office",
                 "english_pronunciation": "Maktab bareed"},
                {"arabic": "سوق کَبِیر", "farsi": "بازار بزرگ", "english": "Big market",
                 "english_pronunciation": "Sooq kabeer"},
            ],
            "sentences": [
                {"arabic": "أَعیشُ فِی المَدِینَةِ.", "farsi": "در شهر زندگی می‌کنم.", "english": "I live in the city.",
                 "english_pronunciation": "A'eeshu fil-madeenati."},
                {"arabic": "القَریَةُ هادِئَةٌ.", "farsi": "روستا آرام است.", "english": "The village is quiet.",
                 "english_pronunciation": "Al-qaryatu haadi'atun."},
                {"arabic": "الشارِعُ طَوِیلٌ.", "farsi": "خیابان طولانی است.", "english": "The street is long.",
                 "english_pronunciation": "Ash-shaari'u taweelun."},
                {"arabic": "المَسجِدُ فِی المَیدانِ.", "farsi": "مسجد در میدان است.",
                 "english": "The mosque is in the square.", "english_pronunciation": "Al-masjidu fil-maydaani."},
                {"arabic": "المُستَشفى قَریبٌ مِنَ المَنزِلِ.", "farsi": "بیمارستان نزدیک خانه است.",
                 "english": "The hospital is near the home.",
                 "english_pronunciation": "Al-mustashfa qareebun min al-manzili."},
                {"arabic": "أَذهَبُ إلى الصَّیدَلِیَّةِ.", "farsi": "به داروخانه می‌روم.",
                 "english": "I go to the pharmacy.", "english_pronunciation": "Adhhabu ila as-saydaliyyati."},
                {"arabic": "المَکتَبَةُ مَفتوحَةٌ.", "farsi": "کتابخانه باز است.", "english": "The library is open.",
                 "english_pronunciation": "Al-maktabatu maftoohatun."},
                {"arabic": "نَأکُلُ فِی المَطعَمِ.", "farsi": "در رستوران غذا می‌خوریم.",
                 "english": "We eat in the restaurant.", "english_pronunciation": "Na'kulu fil-mat'ami."},
                {"arabic": "الحَدِیقَةُ العُمومِیَّةُ جَمیلَةٌ.", "farsi": "پارک عمومی زیبا است.",
                 "english": "The public park is beautiful.",
                 "english_pronunciation": "Al-hadeeqatu al-'umoomiyyatu jameelatun."},
            ]
        },
        "lesson_7": {
            "words": [
                {"arabic": "طَعام", "farsi": "غذا", "english": "Food", "english_pronunciation": "Ta'aam"},
                {"arabic": "ماء", "farsi": "آب", "english": "Water", "english_pronunciation": "Maa'"},
                {"arabic": "حَلیب", "farsi": "شیر", "english": "Milk", "english_pronunciation": "Haleeb"},
                {"arabic": "عَصِیر", "farsi": "آبمیوه", "english": "Juice", "english_pronunciation": "Aseer"},
                {"arabic": "جُبن", "farsi": "پنیر", "english": "Cheese", "english_pronunciation": "Jubn"},
                {"arabic": "زَیت", "farsi": "روغن", "english": "Oil", "english_pronunciation": "Zayt"},
                {"arabic": "سُکَّر", "farsi": "شکر", "english": "Sugar", "english_pronunciation": "Sukkar"},
                {"arabic": "مِلح", "farsi": "نمک", "english": "Salt", "english_pronunciation": "Milh"},
                {"arabic": "خُبز", "farsi": "نان", "english": "Bread", "english_pronunciation": "Khubz"},
                {"arabic": "أَرُزّ", "farsi": "برنج", "english": "Rice", "english_pronunciation": "Aruzz"},
                {"arabic": "مَعکَرونَة", "farsi": "ماکارونی", "english": "Pasta",
                 "english_pronunciation": "Ma'karoona"},
                {"arabic": "فَطور", "farsi": "صبحانه", "english": "Breakfast", "english_pronunciation": "Fatoor"},
                {"arabic": "غَداء", "farsi": "ناهار", "english": "Lunch", "english_pronunciation": "Ghadaa'"},
                {"arabic": "عَشاء", "farsi": "شام", "english": "Dinner", "english_pronunciation": "Ashaa'"},
                {"arabic": "مَائِدَة", "farsi": "سفره", "english": "Table (for dining)",
                 "english_pronunciation": "Maa'ida"},
            ],
            "sentences": [
                {"arabic": "أَأکُلُ الطَّعامَ عَلى المَائِدَةِ.", "farsi": "غذا را روی سفره می‌خورم.",
                 "english": "I eat food on the table.", "english_pronunciation": "A'kulu at-ta'aama ala al-maa'idati."},
                {"arabic": "أَشرَبُ الماءَ بَعدَ الفَطورِ.", "farsi": "بعد از صبحانه آب می‌نوشم.",
                 "english": "I drink water after breakfast.",
                 "english_pronunciation": "Ashrabu al-maa'a ba'da al-fatoori."},
                {"arabic": "الحَلیبُ فِی الثَّلّاجَةِ.", "farsi": "شیر در یخچال است.",
                 "english": "The milk is in the refrigerator.", "english_pronunciation": "Al-haleebu fil-thallajati."},
                {"arabic": "أُحِبُّ العَصِیرَ مَعَ الغَداءِ.", "farsi": "با ناهار آبمیوه دوست دارم.",
                 "english": "I like juice with lunch.", "english_pronunciation": "Uhibbu al-aseera ma'a al-ghadaa'i."},
                {"arabic": "الجُبنُ وَالخُبزُ عَلى المَائِدَةِ.", "farsi": "پنیر و نان روی سفره است.",
                 "english": "The cheese and bread are on the table.",
                 "english_pronunciation": "Al-jubnu wal-khubzu ala al-maa'idati."},
                {"arabic": "أَضَعُ السُّکَّرَ فِی الشَّایِ.", "farsi": "شکر را در چای می‌ریزم.",
                 "english": "I put sugar in the tea.", "english_pronunciation": "Ada'u as-sukkara fish-shaayi."},
                {"arabic": "المَعکَرونَةُ لِلعَشاءِ.", "farsi": "ماکارونی برای شام است.",
                 "english": "The pasta is for dinner.", "english_pronunciation": "Al-ma'kroonatu lil-ashaa'i."},
                {"arabic": "الأَرُزُّ طَیِّبٌ جِدّاً.", "farsi": "برنج خیلی خوشمزه است.",
                 "english": "The rice is very delicious.", "english_pronunciation": "Al-aruzzu tayyibun jiddan."},
            ]
        },
        "lesson_8": {
            "words": [
                {"arabic": "رِیاضَة", "farsi": "ورزش", "english": "Sport", "english_pronunciation": "Riyaada"},
                {"arabic": "کُرَة القَدَم", "farsi": "فوتبال", "english": "Football",
                 "english_pronunciation": "Kurat al-qadam"},
                {"arabic": "کُرَة السَّلَّة", "farsi": "بسکتبال", "english": "Basketball",
                 "english_pronunciation": "Kurat as-salla"},
                {"arabic": "سِباحَة", "farsi": "شنا", "english": "Swimming", "english_pronunciation": "Sibaaha"},
                {"arabic": "مَلعَب", "farsi": "زمین بازی", "english": "Playground", "english_pronunciation": "Mal'ab"},
                {"arabic": "فَرِیق", "farsi": "تیم", "english": "Team", "english_pronunciation": "Fareeq"},
                {"arabic": "لاعِب", "farsi": "بازیکن (مرد)", "english": "Player (male)",
                 "english_pronunciation": "Laa'ib"},
                {"arabic": "لاعِبَة", "farsi": "بازیکن (زن)", "english": "Player (female)",
                 "english_pronunciation": "Laa'iba"},
                {"arabic": "کُرَة", "farsi": "توپ", "english": "Ball", "english_pronunciation": "Kura"},
                {"arabic": "هَدَف", "farsi": "گل (در ورزش)", "english": "Goal", "english_pronunciation": "Hadaf"},
                {"arabic": "مُباراة", "farsi": "مسابقه", "english": "Match", "english_pronunciation": "Mubaaraa"},
                {"arabic": "مِدالِیَّة", "farsi": "مدال", "english": "Medal", "english_pronunciation": "Midaaliyya"},
                {"arabic": "جائِزَة", "farsi": "جایزه", "english": "Prize", "english_pronunciation": "Jaa'iza"},
                {"arabic": "تَمرِین", "farsi": "تمرین", "english": "Training", "english_pronunciation": "Tamreen"},
                {"arabic": "مُدَرِّب", "farsi": "مربی (مرد)", "english": "Coach (male)",
                 "english_pronunciation": "Mudarrib"},
            ],
            "sentences": [
                {"arabic": "أُحِبُّ الرِّیاضَةَ.", "farsi": "ورزش را دوست دارم.", "english": "I love sports.",
                 "english_pronunciation": "Uhibbu ar-riyaadata."},
                {"arabic": "أَلعَبُ کُرَةَ القَدَمِ فِی المَلعَبِ.", "farsi": "فوتبال را در زمین بازی می‌کنم.",
                 "english": "I play football in the playground.",
                 "english_pronunciation": "Al'abu kurat al-qadami fil-mal'abi."},
                {"arabic": "الفَرِیقُ یَفوزُ فِی المُباراةِ.", "farsi": "تیم در مسابقه برنده می‌شود.",
                 "english": "The team wins the match.", "english_pronunciation": "Al-fareequ yafuzu fil-mubaaraati."},
                {"arabic": "اللاعِبَةُ تَسجِّلُ هَدَفاً.", "farsi": "بازیکن (زن) گل می‌زند.",
                 "english": "The player (female) scores a goal.",
                 "english_pronunciation": "Al-laa'ibatu tasjilu hadafan."},
                {"arabic": "السِّباحَةُ رِیاضَةٌ مُفِیدَةٌ.", "farsi": "شنا ورزش مفیدی است.",
                 "english": "Swimming is a useful sport.",
                 "english_pronunciation": "As-sibaahatu riyaadatun mufeedatun."},
                {"arabic": "المُدَرِّبُ یُدَرِّبُ الفَرِیقَ.", "farsi": "مربی تیم را تمرین می‌دهد.",
                 "english": "The coach trains the team.",
                 "english_pronunciation": "Al-mudarribu yudarribu al-fareeqa."},
                {"arabic": "فَزتُ بِمِدالِیَّةٍ فِی المُباراةِ.", "farsi": "در مسابقه مدال بردم.",
                 "english": "I won a medal in the match.",
                 "english_pronunciation": "Faztu bi-midaaliyyatin fil-mubaaraati."},
                {"arabic": "التَّمرِینُ یَبدَأُ صَباحاً.", "farsi": "تمرین صبح شروع می‌شود.",
                 "english": "The training starts in the morning.",
                 "english_pronunciation": "At-tamreenu yabda'u sabaahan."},
            ]
        }
    },


    "8th_grade": {
        "lesson_1": {
            "words": [
                {"arabic": "جُملَة فِعلیَّة", "farsi": "جمله فعلیه", "english": "Verbal Sentence", "english_pronunciation": "Jumla fi'liyya"},
                {"arabic": "جُملَة اِسمیَّة", "farsi": "جمله اسمیه", "english": "Nominal Sentence", "english_pronunciation": "Jumla ismiyya"},
                {"arabic": "فِعل ماضی", "farsi": "فعل ماضی", "english": "Past Tense Verb", "english_pronunciation": "Fi'lun madin"},
                {"arabic": "فِعل مُضارِع", "farsi": "فعل مضارع", "english": "Present Tense Verb", "english_pronunciation": "Fi'lun mudari'un"},
                {"arabic": "فاعِل", "farsi": "فاعل", "english": "Subject/Doer", "english_pronunciation": "Fa-il"},
                {"arabic": "مَفعُول بِه", "farsi": "مفعول", "english": "Object", "english_pronunciation": "Maf-ool bi-hi"},
                {"arabic": "حَرف جَرّ", "farsi": "حرف اضافه", "english": "Preposition", "english_pronunciation": "Harf jarr"},
                {"arabic": "فِی", "farsi": "در", "english": "In", "english_pronunciation": "Fee"},
                {"arabic": "إلى", "farsi": "به سوی", "english": "To", "english_pronunciation": "Ila"},
                {"arabic": "عَلى", "farsi": "بر", "english": "On", "english_pronunciation": "Ala"},
                {"arabic": "مِن", "farsi": "از", "english": "From", "english_pronunciation": "Min"},
                {"arabic": "بِ", "farsi": "با", "english": "With", "english_pronunciation": "Bi"},
                {"arabic": "عَن", "farsi": "درباره", "english": "About", "english_pronunciation": "An"},
                {"arabic": "مَعَ", "farsi": "همراه", "english": "With", "english_pronunciation": "Ma'a"},
                {"arabic": "لِ", "farsi": "برای", "english": "For", "english_pronunciation": "Li"},
            ],
            "sentences": [
                {"arabic": "اَلْعِلْمُ نورٌ.", "farsi": "دانش، نور است.", "english": "Knowledge is light.", "english_pronunciation": "Al-'ilmu noorun."},
                {"arabic": "یَکتُبُ الطّالِبُ الدَّرسَ.", "farsi": "دانش‌آموز درس را می‌نویسد.", "english": "The student writes the lesson.", "english_pronunciation": "Yaktubu at-talibu ad-darsa."},
                {"arabic": "شَرِبَ المَریضُ الدَّواءَ.", "farsi": "بیمار دارو را نوشید.", "english": "The patient drank the medicine.", "english_pronunciation": "Shariba al-mareedu ad-dawa'a."},
                {"arabic": "ذَهَبَ التِّلمیذُ إلى المَدرَسَةِ.", "farsi": "دانش‌آموز به مدرسه رفت.", "english": "The student went to school.", "english_pronunciation": "Dhahaba at-tilmeezu ila al-madrasati."},
                {"arabic": "الکِتابُ عَلى المَکتَبِ.", "farsi": "کتاب روی میز است.", "english": "The book is on the desk.", "english_pronunciation": "Al-kitabu ala al-maktabi."},
                {"arabic": "یَجلِسُ الأُستاذُ فِی القاعَةِ.", "farsi": "استاد در کلاس می‌نشیند.", "english": "The teacher sits in the classroom.", "english_pronunciation": "Yajlisu al-ustadhu fil-qaa'ati."},
                {"arabic": "أَتَيتُ مِنَ السُّوقِ.", "farsi": "از بازار آمدم.", "english": "I came from the market.", "english_pronunciation": "Ataytu mina as-sooqi."},
                {"arabic": "أَتَکلَّمُ مَعَ الصَّدِیقِ.", "farsi": "با دوست صحبت می‌کنم.", "english": "I talk with the friend.", "english_pronunciation": "Atakallamu ma'a as-sadeeqi."},
                {"arabic": "أَسأَلُ عَنِ الدَّرسِ.", "farsi": "درباره درس سؤالم.", "english": "I ask about the lesson.", "english_pronunciation": "As'alu an ad-darsi."},
            ]
        },
        "lesson_2": {
            "words": [
                {"arabic": "زَمان", "farsi": "زمان", "english": "Time", "english_pronunciation": "Zaman"},
                {"arabic": "یَوم", "farsi": "روز", "english": "Day", "english_pronunciation": "Yawm"},
                {"arabic": "أُسبوع", "farsi": "هفته", "english": "Week", "english_pronunciation": "Usboo'"},
                {"arabic": "شَهر", "farsi": "ماه", "english": "Month", "english_pronunciation": "Shahr"},
                {"arabic": "ساعَة", "farsi": "ساعت", "english": "Hour", "english_pronunciation": "Saa'a"},
                {"arabic": "دَقِیقَة", "farsi": "دقیقه", "english": "Minute", "english_pronunciation": "Daqeeqa"},
                {"arabic": "غَداً", "farsi": "فردا", "english": "Tomorrow", "english_pronunciation": "Ghadan"},
                {"arabic": "أَمس", "farsi": "دیروز", "english": "Yesterday", "english_pronunciation": "Ams"},
                {"arabic": "الآن", "farsi": "اکنون", "english": "Now", "english_pronunciation": "Al-aan"},
                {"arabic": "صَباحاً", "farsi": "صبح", "english": "Morning", "english_pronunciation": "Sabaahan"},
                {"arabic": "مَساءً", "farsi": "عصر", "english": "Evening", "english_pronunciation": "Masaa'an"},
                {"arabic": "لَیل", "farsi": "شب", "english": "Night", "english_pronunciation": "Layl"},
                {"arabic": "نَهار", "farsi": "روز (به معنای روشنایی)", "english": "Daytime", "english_pronunciation": "Nahaar"},
                {"arabic": "سَنَة", "farsi": "سال", "english": "Year", "english_pronunciation": "Sana"},
                {"arabic": "تَقوِیم", "farsi": "تقویم", "english": "Calendar", "english_pronunciation": "Taqweem"},
            ],
            "sentences": [
                {"arabic": "الآنَ السَّاعَةُ الخامِسَةُ.", "farsi": "اکنون ساعت پنج است.", "english": "Now it is five o'clock.", "english_pronunciation": "Al-aana as-saa'atu al-khaamisatu."},
                {"arabic": "ذَهَبتُ إلى المَدرَسَةِ أَمس.", "farsi": "دیروز به مدرسه رفتم.", "english": "I went to school yesterday.", "english_pronunciation": "Dhahabtu ila al-madrasati ams."},
                {"arabic": "سَأَذهَبُ إلى الحَدِیقَةِ غَداً.", "farsi": "فردا به باغ می‌روم.", "english": "I will go to the garden tomorrow.", "english_pronunciation": "Sa-adhhabu ila al-hadeeqati ghadan."},
                {"arabic": "الدَّرسُ یَبدَأُ بَعدَ دَقِیقَةٍ.", "farsi": "درس بعد از یک دقیقه شروع می‌شود.", "english": "The lesson starts after one minute.", "english_pronunciation": "Ad-darsu yabda'u ba'da daqeeqatin."},
                {"arabic": "یَدرُسُ التِّلمیذُ یَومَ الأَحَدِ.", "farsi": "دانش‌آموز روز یکشنبه درس می‌خواند.", "english": "The student studies on Sunday.", "english_pronunciation": "Yadrusu at-tilmeezu yawma al-ahadi."},
                {"arabic": "أَجتمِعُ مَعَ الصَّدِیقِ مَساءً.", "farsi": "عصر با دوست ملاقات می‌کنم.", "english": "I meet with the friend in the evening.", "english_pronunciation": "Aj-tami'u ma'a as-sadeeqi masaa'an."},
                {"arabic": "اللَّیلُ هادِئٌ.", "farsi": "شب آرام است.", "english": "The night is quiet.", "english_pronunciation": "Al-laylu haadi'un."},
                {"arabic": "أَشترِی تَقوِیماً جَدِیداً کُلَّ سَنَةٍ.", "farsi": "هر سال تقویم جدید می‌خرم.", "english": "I buy a new calendar every year.", "english_pronunciation": "Ashtaree taqweeman jadeedan kulla sanatin."},
            ]
        },
        "lesson_3": {
            "words": [
                {"arabic": "دَرس", "farsi": "درس", "english": "Lesson", "english_pronunciation": "Dars"},
                {"arabic": "کِتابَة", "farsi": "نوشتن", "english": "Writing", "english_pronunciation": "Kitaaba"},
                {"arabic": "قِراءَة", "farsi": "خواندن", "english": "Reading", "english_pronunciation": "Qiraa'a"},
                {"arabic": "مُذاکَرَة", "farsi": "مطالعه", "english": "Studying", "english_pronunciation": "Mudhaakara"},
                {"arabic": "اِمتِحان", "farsi": "امتحان", "english": "Exam", "english_pronunciation": "Imtihaan"},
                {"arabic": "واجِب", "farsi": "تکلیف", "english": "Homework", "english_pronunciation": "Waajib"},
                {"arabic": "سُؤال", "farsi": "سوال", "english": "Question", "english_pronunciation": "Su'aal"},
                {"arabic": "جَواب", "farsi": "جواب", "english": "Answer", "english_pronunciation": "Jawaab"},
                {"arabic": "مُمتاز", "farsi": "عالی", "english": "Excellent", "english_pronunciation": "Mumtaaz"},
                {"arabic": "جَیِّد", "farsi": "خوب", "english": "Good", "english_pronunciation": "Jayyid"},
                {"arabic": "صَعب", "farsi": "سخت", "english": "Difficult", "english_pronunciation": "Sa'b"},
                {"arabic": "سَهل", "farsi": "آسان", "english": "Easy", "english_pronunciation": "Sahl"},
                {"arabic": "مُذَکِّر", "farsi": "یادآور", "english": "Reminder", "english_pronunciation": "Mudhakkir"},
                {"arabic": "دَفتَر", "farsi": "دفتر", "english": "Notebook", "english_pronunciation": "Daftar"},
                {"arabic": "مُلاحَظَة", "farsi": "یادداشت", "english": "Note", "english_pronunciation": "Mulaahaza"},
            ],
            "sentences": [
                {"arabic": "أَدرُسُ الدَّرسَ کُلَّ یَومٍ.", "farsi": "هر روز درس می‌خوانم.", "english": "I study the lesson every day.", "english_pronunciation": "Adrusu ad-darsa kulla yawmin."},
                {"arabic": "التِّلمیذَةُ تَکتُبُ الواجِبَ.", "farsi": "دانش‌آموز (دختر) تکلیف را می‌نویسد.", "english": "The student (female) writes the homework.", "english_pronunciation": "At-tilmeezatu taktubu al-waajiba."},
                {"arabic": "الاِمتِحانُ صَعبٌ.", "farsi": "امتحان سخت است.", "english": "The exam is difficult.", "english_pronunciation": "Al-imtihaanu sa'bun."},
                {"arabic": "أَسأَلُ سُؤالاً عَنِ الدَّرسِ.", "farsi": "سوالی درباره درس می‌پرسم.", "english": "I ask a question about the lesson.", "english_pronunciation": "As'alu su'aalan an ad-darsi."},
                {"arabic": "الجَوابُ مُمتازٌ.", "farsi": "جواب عالی است.", "english": "The answer is excellent.", "english_pronunciation": "Al-jawaabu mumtaazun."},
                {"arabic": "القِراءَةُ سَهلَةٌ.", "farsi": "خواندن آسان است.", "english": "Reading is easy.", "english_pronunciation": "Al-qiraa'atu sahlatun."},
                {"arabic": "أَکتُبُ مُلاحَظَةً فِی الدَّفتَرِ.", "farsi": "یادداشتی در دفتر می‌نویسم.", "english": "I write a note in the notebook.", "english_pronunciation": "Aktubu mulaahazatan fid-daftari."},
                {"arabic": "المُذَکِّرُ یُساعِدُ التِّلمیذَ.", "farsi": "یادآور به دانش‌آموز کمک می‌کند.", "english": "The reminder helps the student.", "english_pronunciation": "Al-mudhakkiru yusa'idu at-tilmeedha."},
            ]
        },
        "lesson_4": {
            "words": [
                {"arabic": "طَبِیب", "farsi": "پزشک (مرد)", "english": "Doctor (male)", "english_pronunciation": "Tabeeb"},
                {"arabic": "طَبِیبَة", "farsi": "پزشک (زن)", "english": "Doctor (female)", "english_pronunciation": "Tabeeba"},
                {"arabic": "مُهَندِس", "farsi": "مهندس (مرد)", "english": "Engineer (male)", "english_pronunciation": "Muhandis"},
                {"arabic": "مُهَندِسَة", "farsi": "مهندس (زن)", "english": "Engineer (female)", "english_pronunciation": "Muhandisa"},
                {"arabic": "مُحامٍ", "farsi": "وکیل (مرد)", "english": "Lawyer (male)", "english_pronunciation": "Muhaamin"},
                {"arabic": "مُحامِیَة", "farsi": "وکیل (زن)", "english": "Lawyer (female)", "english_pronunciation": "Muhaamiya"},
                {"arabic": "مِهنَة", "farsi": "حرفه", "english": "Profession", "english_pronunciation": "Mihna"},
                {"arabic": "عَمَل", "farsi": "کار", "english": "Work", "english_pronunciation": "Amal"},
                {"arabic": "مَکتَب", "farsi": "دفتر کار", "english": "Office", "english_pronunciation": "Maktab"},
                {"arabic": "مُوَظَّف", "farsi": "کارمند (مرد)", "english": "Employee (male)", "english_pronunciation": "Muwazzaf"},
                {"arabic": "مُوَظَّفَة", "farsi": "کارمند (زن)", "english": "Employee (female)", "english_pronunciation": "Muwazzafa"},
                {"arabic": "مُدِیر", "farsi": "مدیر (مرد)", "english": "Manager (male)", "english_pronunciation": "Mudeer"},
                {"arabic": "مُدِیرَة", "farsi": "مدیر (زن)", "english": "Manager (female)", "english_pronunciation": "Mudeera"},
                {"arabic": "مُزارِع", "farsi": "کشاورز", "english": "Farmer", "english_pronunciation": "Muzaari'"},
                {"arabic": "تاجِر", "farsi": "تاجر", "english": "Merchant", "english_pronunciation": "Taajir"},
            ],
            "sentences": [
                {"arabic": "أَبِی طَبِیبٌ فِی المُستَشفى.", "farsi": "پدرم پزشک در بیمارستان است.", "english": "My father is a doctor in the hospital.", "english_pronunciation": "Abee tabeebun fil-mustashfa."},
                {"arabic": "المُهَندِسَةُ تَعمَلُ فِی المَکتَبِ.", "farsi": "مهندس (زن) در دفتر کار می‌کند.", "english": "The engineer (female) works in the office.", "english_pronunciation": "Al-muhandisatu ta'malu fil-maktabi."},
                {"arabic": "المُحامِیَةُ نَشِیطَةٌ.", "farsi": "وکیل (زن) کوشا است.", "english": "The lawyer (female) is active.", "english_pronunciation": "Al-muhaamiyatu nashitatun."},
                {"arabic": "أَحبُّ مِهنَةَ التَّدرِیسِ.", "farsi": "حرفه تدریس را دوست دارم.", "english": "I love the teaching profession.", "english_pronunciation": "Uhibbu mihnata at-tadreesi."},
                {"arabic": "العَمَلُ فِی المَکتَبِ مُمتِعٌ.", "farsi": "کار در دفتر لذت‌بخش است.", "english": "Work in the office is enjoyable.", "english_pronunciation": "Al-amalu fil-maktabi mumti'un."},
                {"arabic": "المُوَظَّفُ یَجلِسُ فِی المَکتَبِ.", "farsi": "کارمند در دفتر می‌نشیند.", "english": "The employee sits in the office.", "english_pronunciation": "Al-muwazzafu yajlisu fil-maktabi."},
                {"arabic": "المُدِیرَةُ تُدَبِّرُ العَمَلَ.", "farsi": "مدیر (زن) کار را مدیریت می‌کند.", "english": "The manager (female) manages the work.", "english_pronunciation": "Al-mudeeratu tudabbiru al-amala."},
                {"arabic": "المُزارِعُ یَزرَعُ الحَدِیقَةَ.", "farsi": "کشاورز باغ را می‌کارد.", "english": "The farmer plants the garden.", "english_pronunciation": "Al-muzaari'u yazra'u al-hadeeqata."},
            ]
        },
        "lesson_5": {
            "words": [
                {"arabic": "سَفَر", "farsi": "سفر", "english": "Travel", "english_pronunciation": "Safar"},
                {"arabic": "طَائِرَة", "farsi": "هواپیما", "english": "Airplane", "english_pronunciation": "Taa'ira"},
                {"arabic": "قِطار", "farsi": "قطار", "english": "Train", "english_pronunciation": "Qitaar"},
                {"arabic": "حافِلَة", "farsi": "اتوبوس", "english": "Bus", "english_pronunciation": "Haafila"},
                {"arabic": "مَدِینَة", "farsi": "شهر", "english": "City", "english_pronunciation": "Madeena"},
                {"arabic": "قَریَة", "farsi": "روستا", "english": "Village", "english_pronunciation": "Qarya"},
                {"arabic": "جَواز سَفَر", "farsi": "گذرنامه", "english": "Passport", "english_pronunciation": "Jawaaz safar"},
                {"arabic": "حَقِیبَة سَفَر", "farsi": "چمدان", "english": "Suitcase", "english_pronunciation": "Haqeebat safar"},
                {"arabic": "مَطار", "farsi": "فرودگاه", "english": "Airport", "english_pronunciation": "Mataar"},
                {"arabic": "مَحَطَّة القِطار", "farsi": "ایستگاه قطار", "english": "Train station", "english_pronunciation": "Mahattat al-qitaar"},
                {"arabic": "تَذکِرَة", "farsi": "بلیط", "english": "Ticket", "english_pronunciation": "Tadhkira"},
                {"arabic": "سائِق", "farsi": "راننده (مرد)", "english": "Driver (male)", "english_pronunciation": "Saa'iq"},
                {"arabic": "راکِب", "farsi": "مسافر", "english": "Passenger", "english_pronunciation": "Raakib"},
                {"arabic": "وِجهَة", "farsi": "مقصد", "english": "Destination", "english_pronunciation": "Wajha"},
                {"arabic": "رِحلَة", "farsi": "سفر (مسافرت)", "english": "Trip", "english_pronunciation": "Rihla"},
            ],
            "sentences": [
                {"arabic": "أَسافِرُ بِالطَّائِرَةِ.", "farsi": "با هواپیما سفر می‌کنم.", "english": "I travel by airplane.", "english_pronunciation": "Asaafiru bit-taa'irati."},
                {"arabic": "القِطارُ یَذهَبُ إلى المَدِینَةِ.", "farsi": "قطار به شهر می‌رود.", "english": "The train goes to the city.", "english_pronunciation": "Al-qitaaru yadhhabu ila al-madeenati."},
                {"arabic": "الحافِلَةُ فِی القَریَةِ.", "farsi": "اتوبوس در روستا است.", "english": "The bus is in the village.", "english_pronunciation": "Al-haafilatu fil-qaryati."},
                {"arabic": "جَوازُ السَّفَرِ مَعِی.", "farsi": "گذرنامه همراه من است.", "english": "The passport is with me.", "english_pronunciation": "Jawaazu as-safari ma'ee."},
                {"arabic": "حَقِیبَةُ السَّفَرِ ثَقِیلَةٌ.", "farsi": "چمدان سنگین است.", "english": "The suitcase is heavy.", "english_pronunciation": "Haqeebatu as-safari thaqeelatun."},
                {"arabic": "أَشترِی تَذکِرَةً مِنَ المَطارِ.", "farsi": "بلیط را از فرودگاه می‌خرم.", "english": "I buy a ticket from the airport.", "english_pronunciation": "Ashtaree tadhkiratan mina al-mataari."},
                {"arabic": "السَّائِقُ یَقودُ الحافِلَةَ.", "farsi": "راننده اتوبوس را می‌راند.", "english": "The driver drives the bus.", "english_pronunciation": "As-saa'iqu yaqudu al-haafilata."},
                {"arabic": "الرَّاکِبُ فِی المَحَطَّةِ.", "farsi": "مسافر در ایستگاه است.", "english": "The passenger is in the station.", "english_pronunciation": "Ar-raakibu fil-mahattati."},
            ]
        },
        "lesson_6": {
            "words": [
                {"arabic": "طَقس", "farsi": "هوا", "english": "Weather", "english_pronunciation": "Taqs"},
                {"arabic": "شَمس", "farsi": "خورشید", "english": "Sun", "english_pronunciation": "Shams"},
                {"arabic": "قَمَر", "farsi": "ماه", "english": "Moon", "english_pronunciation": "Qamar"},
                {"arabic": "مَطَر", "farsi": "باران", "english": "Rain", "english_pronunciation": "Matar"},
                {"arabic": "غَیم", "farsi": "ابر", "english": "Cloud", "english_pronunciation": "Ghaym"},
                {"arabic": "رِیاح", "farsi": "باد", "english": "Wind", "english_pronunciation": "Riyaah"},
                {"arabic": "بَرد", "farsi": "سرما", "english": "Cold", "english_pronunciation": "Bard"},
                {"arabic": "حَرّ", "farsi": "گرما", "english": "Heat", "english_pronunciation": "Harr"},
                {"arabic": "ثَلج", "farsi": "برف", "english": "Snow", "english_pronunciation": "Thalj"},
                {"arabic": "رَعد", "farsi": "رعد", "english": "Thunder", "english_pronunciation": "Ra'd"},
                {"arabic": "بَرق", "farsi": "صاعقه", "english": "Lightning", "english_pronunciation": "Barq"},
                {"arabic": "رَطوبَة", "farsi": "رطوبت", "english": "Humidity", "english_pronunciation": "Rutooba"},
                {"arabic": "مِظَلَّة", "farsi": "چتر", "english": "Umbrella", "english_pronunciation": "Mizalla"},
                {"arabic": "جَوّ", "farsi": "جو", "english": "Atmosphere", "english_pronunciation": "Jaww"},
                {"arabic": "دَرَجَة الحَرارَة", "farsi": "درجه حرارت", "english": "Temperature", "english_pronunciation": "Darajat al-harara"},
            ],
            "sentences": [
                {"arabic": "الطَّقسُ اليَومَ حارٌّ.", "farsi": "هوا امروز گرم است.", "english": "The weather today is hot.", "english_pronunciation": "At-taqsu al-yawma harrun."},
                {"arabic": "الشَّمسُ مُشرِقَةٌ فِی السَّماءِ.", "farsi": "خورشید در آسمان می‌درخشد.", "english": "The sun is shining in the sky.", "english_pronunciation": "Ash-shamsu mushriqatun fis-samaa'i."},
                {"arabic": "المَطَرُ یَهطُلُ فِی المَساءِ.", "farsi": "باران در عصر می‌بارد.", "english": "The rain falls in the evening.", "english_pronunciation": "Al-mataru yahtulu fil-masaa'i."},
                {"arabic": "الغَیمُ یُغَطِّی السَّماءَ.", "farsi": "ابر آسمان را می‌پوشاند.", "english": "The cloud covers the sky.", "english_pronunciation": "Al-ghaymu yughatti as-samaa'a."},
                {"arabic": "الرِّیاحُ قَوِیَّةٌ اليَومَ.", "farsi": "باد امروز قوی است.", "english": "The wind is strong today.", "english_pronunciation": "Ar-riyaahu qawiyyatun al-yawma."},
                {"arabic": "الثَّلجُ یَهطُلُ فِی الشِّتاءِ.", "farsi": "برف در زمستان می‌بارد.", "english": "The snow falls in winter.", "english_pronunciation": "Ath-thalju yahtulu fish-shitaa'i."},
                {"arabic": "أَحمِلُ مِظَلَّةً عِندَ المَطَرِ.", "farsi": "وقتی باران می‌بارد چتر می‌برم.", "english": "I carry an umbrella when it rains.", "english_pronunciation": "Ahmilu mizallatan 'inda al-matari."},
                {"arabic": "دَرَجَةُ الحَرارَةِ مُرتَفِعَةٌ.", "farsi": "درجه حرارت بالا است.", "english": "The temperature is high.", "english_pronunciation": "Darajatu al-haraarati murtafi'atun."},
            ]
        },
        "lesson_7": {
            "words": [
                {"arabic": "صِحَّة", "farsi": "سلامتی", "english": "Health", "english_pronunciation": "Sihha"},
                {"arabic": "مَرَض", "farsi": "بیماری", "english": "Illness", "english_pronunciation": "Marad"},
                {"arabic": "دَواء", "farsi": "دارو", "english": "Medicine", "english_pronunciation": "Dawaa'"},
                {"arabic": "مَرِیض", "farsi": "بیمار (مرد)", "english": "Patient (male)", "english_pronunciation": "Mareed"},
                {"arabic": "مَرِیضَة", "farsi": "بیمار (زن)", "english": "Patient (female)", "english_pronunciation": "Mareeda"},
                {"arabic": "مُستَشفى", "farsi": "بیمارستان", "english": "Hospital", "english_pronunciation": "Mustashfa"},
                {"arabic": "طَبِیب أَسنان", "farsi": "دندانپزشک", "english": "Dentist", "english_pronunciation": "Tabeeb asnaan"},
                {"arabic": "أَلم", "farsi": "درد", "english": "Pain", "english_pronunciation": "Alam"},
                {"arabic": "رَأس", "farsi": "سر", "english": "Head", "english_pronunciation": "Ra's"},
                {"arabic": "مَعِدَة", "farsi": "معده", "english": "Stomach", "english_pronunciation": "Ma'ida"},
                {"arabic": "قَلب", "farsi": "قلب", "english": "Heart", "english_pronunciation": "Qalb"},
                {"arabic": "فَحص", "farsi": "معاینه", "english": "Examination", "english_pronunciation": "Fahs"},
                {"arabic": "وَصفَة", "farsi": "نسخه", "english": "Prescription", "english_pronunciation": "Wasfa"},
                {"arabic": "رِیاضَة", "farsi": "ورزش", "english": "Exercise", "english_pronunciation": "Riyaada"},
                {"arabic": "نَظافَة", "farsi": "نظافت", "english": "Cleanliness", "english_pronunciation": "Nazaafa"},
            ],
            "sentences": [
                {"arabic": "الصِّحَّةُ نِعمَةٌ عَظِیمَةٌ.", "farsi": "سلامتی نعمت بزرگی است.", "english": "Health is a great blessing.", "english_pronunciation": "As-sihhatu ni'matun 'azeematun."},
                {"arabic": "المَرِیضُ فِی المُستَشفى.", "farsi": "بیمار در بیمارستان است.", "english": "The patient is in the hospital.", "english_pronunciation": "Al-mareedu fil-mustashfa."},
                {"arabic": "أَشعُرُ بِأَلمٍ فِی الرَّأسِ.", "farsi": "در سرم درد احساس می‌کنم.", "english": "I feel pain in the head.", "english_pronunciation": "Ash'uru bi-alamin fir-ra'si."},
                {"arabic": "الطَّبِیبُ یَفحَصُ المَرِیضَةَ.", "farsi": "پزشک بیمار (زن) را معاینه می‌کند.", "english": "The doctor examines the patient (female).", "english_pronunciation": "At-tabeebu yafhasu al-mareedata."},
                {"arabic": "أَتَناوَلُ الدَّواءَ کُلَّ یَومٍ.", "farsi": "هر روز دارو مصرف می‌کنم.", "english": "I take the medicine every day.", "english_pronunciation": "Atanawalu ad-dawaa'a kulla yawmin."},
                {"arabic": "الرِّیاضَةُ تُحافِظُ عَلى الصِّحَّةِ.", "farsi": "ورزش از سلامتی محافظت می‌کند.", "english": "Exercise maintains health.", "english_pronunciation": "Ar-riyaadatu tuhaafizu ala as-sihhati."},
                {"arabic": "النَّظافَةُ مِنَ الإِیمانِ.", "farsi": "نظافت از ایمان است.", "english": "Cleanliness is part of faith.", "english_pronunciation": "An-nazaafatu mina al-eemaani."},
                {"arabic": "الطَّبِیبُ یَکتُبُ وَصفَةً.", "farsi": "پزشک نسخه می‌نویسد.", "english": "The doctor writes a prescription.", "english_pronunciation": "At-tabeebu yaktubu wasfatan."},
            ]
        },
        "lesson_8": {
            "words": [
                {"arabic": "أَخلاق", "farsi": "اخلاق", "english": "Morals", "english_pronunciation": "Akhlaaq"},
                {"arabic": "صِدق", "farsi": "راستگویی", "english": "Honesty", "english_pronunciation": "Sidq"},
                {"arabic": "کَذِب", "farsi": "دروغ", "english": "Lie", "english_pronunciation": "Kadhib"},
                {"arabic": "أَمانَة", "farsi": "امانت", "english": "Trustworthiness", "english_pronunciation": "Amaana"},
                {"arabic": "خِیانَة", "farsi": "خیانت", "english": "Betrayal", "english_pronunciation": "Khiyaana"},
                {"arabic": "عَدل", "farsi": "عدالت", "english": "Justice", "english_pronunciation": "Adl"},
                {"arabic": "ظُلم", "farsi": "ستم", "english": "Injustice", "english_pronunciation": "Dhulm"},
                {"arabic": "إِحسان", "farsi": "نیکوکاری", "english": "Kindness", "english_pronunciation": "Ihsaan"},
                {"arabic": "شُکر", "farsi": "سپاس", "english": "Gratitude", "english_pronunciation": "Shukr"},
                {"arabic": "صَبر", "farsi": "صبر", "english": "Patience", "english_pronunciation": "Sabr"},
                {"arabic": "حَسَد", "farsi": "حسادت", "english": "Envy", "english_pronunciation": "Hasad"},
                {"arabic": "تَواضُع", "farsi": "فروتنی", "english": "Humility", "english_pronunciation": "Tawaadu'"},
                {"arabic": "کِبر", "farsi": "تکبر", "english": "Arrogance", "english_pronunciation": "Kibr"},
                {"arabic": "مَحَبَّة", "farsi": "محبت", "english": "Love", "english_pronunciation": "Mahabba"},
                {"arabic": "مُساعَدَة", "farsi": "کمک", "english": "Help", "english_pronunciation": "Musa'ada"},
            ],
            "sentences": [
                {"arabic": "الصِّدقُ یُنقِذُ الإِنسانَ.", "farsi": "راستگویی انسان را نجات می‌دهد.", "english": "Honesty saves a person.", "english_pronunciation": "As-sidqu yunqidhu al-insaana."},
                {"arabic": "الکَذِبُ یُؤدِّی إلى الخِیانَةِ.", "farsi": "دروغ به خیانت منجر می‌شود.", "english": "Lying leads to betrayal.", "english_pronunciation": "Al-kadhibu yu'uddee ila al-khiyaanati."},
                {"arabic": "الأَمانَةُ صِفَةٌ حَمِیدَةٌ.", "farsi": "امانت صفتی پسندیده است.", "english": "Trustworthiness is a commendable trait.", "english_pronunciation": "Al-amaanatu sifatun hameedatun."},
                {"arabic": "الظُّلمُ مَمنوعٌ فِی الإِسلامِ.", "farsi": "ستم در اسلام ممنوع است.", "english": "Injustice is forbidden in Islam.", "english_pronunciation": "Adh-dhulmu mamnoo'un fil-islaami."},
                {"arabic": "الإِحسانُ یَجلِبُ المَحَبَّةَ.", "farsi": "نیکوکاری محبت می‌آورد.", "english": "Kindness brings love.", "english_pronunciation": "Al-ihsaanu yajlibu al-mahabbata."},
                {"arabic": "الشُّکرُ یَزِیدُ النِّعمَةَ.", "farsi": "سپاس نعمت را زیاد می‌کند.", "english": "Gratitude increases blessings.", "english_pronunciation": "Ash-shukru yazeedu an-ni'mata."},
                {"arabic": "الصَّبرُ مِفتاحُ الفَرَجِ.", "farsi": "صبر کلید گشایش است.", "english": "Patience is the key to relief.", "english_pronunciation": "As-sabru miftaahu al-faraji."},
                {"arabic": "التَّواضُعُ یَرفَعُ الإِنسانَ.", "farsi": "فروتنی انسان را بالا می‌برد.", "english": "Humility elevates a person.", "english_pronunciation": "At-tawaadu'u yarfa'u al-insaana."},
            ]
        }
    },

    "9th_grade": {
        "lesson_1": {
            "words": [
                {"arabic": "مُبتَدَأ", "farsi": "مبتدا", "english": "Subject (of a nominal sentence)", "english_pronunciation": "Mubtada"},
                {"arabic": "خَبَر", "farsi": "خبر", "english": "Predicate", "english_pronunciation": "Khabar"},
                {"arabic": "فِعل أَمر", "farsi": "فعل امر", "english": "Imperative Verb", "english_pronunciation": "Fi'l amr"},
                {"arabic": "مَمنوع مِنَ الصَّرف", "farsi": "ممنوع از صرف", "english": "Non-declinable", "english_pronunciation": "Mamnoo' min as-sarf"},
                {"arabic": "مَعرِفَة", "farsi": "معرفه", "english": "Definite", "english_pronunciation": "Ma'rifa"},
                {"arabic": "نَکرَة", "farsi": "نکره", "english": "Indefinite", "english_pronunciation": "Nakira"},
                {"arabic": "ضَمِیر", "farsi": "ضمیر", "english": "Pronoun", "english_pronunciation": "Dameer"},
                {"arabic": "أَنا", "farsi": "من", "english": "I", "english_pronunciation": "Ana"},
                {"arabic": "أَنتَ", "farsi": "تو (مذکر)", "english": "You (masculine)", "english_pronunciation": "Anta"},
                {"arabic": "أَنتِ", "farsi": "تو (مؤنث)", "english": "You (feminine)", "english_pronunciation": "Anti"},
                {"arabic": "هُوَ", "farsi": "او (مذکر)", "english": "He", "english_pronunciation": "Huwa"},
                {"arabic": "هِیَ", "farsi": "او (مؤنث)", "english": "She", "english_pronunciation": "Hiya"},
                {"arabic": "نَحنُ", "farsi": "ما", "english": "We", "english_pronunciation": "Nahnu"},
                {"arabic": "أَنتُما", "farsi": "شما (دو نفر)", "english": "You (dual)", "english_pronunciation": "Antuma"},
                {"arabic": "هُما", "farsi": "آن‌ها (دو نفر)", "english": "They (dual)", "english_pronunciation": "Huma"},
            ],
            "sentences": [
                {"arabic": "الطَّالِبُ مُجتَهِدٌ.", "farsi": "دانش‌آموز کوشا است.", "english": "The student is diligent.", "english_pronunciation": "At-taalibu mujtahidun."},
                {"arabic": "اُکتُبْ الدَّرسَ!", "farsi": "درس را بنویس!", "english": "Write the lesson!", "english_pronunciation": "Uktub ad-darsa!"},
                {"arabic": "أَنا طَالِبٌ فِی الصَّفِّ التّاسِعِ.", "farsi": "من دانش‌آموز کلاس نهم هستم.", "english": "I am a student in the ninth grade.", "english_pronunciation": "Ana taalibun fis-saffi at-taasi'i."},
                {"arabic": "هُوَ یَدرُسُ العَرَبِیَّةَ.", "farsi": "او عربی می‌خواند.", "english": "He studies Arabic.", "english_pronunciation": "Huwa yadrusu al-'arabiyyata."},
                {"arabic": "هِیَ مُعَلِّمَةٌ جَدِیدَةٌ.", "farsi": "او معلم جدیدی است.", "english": "She is a new teacher.", "english_pronunciation": "Hiya mu'allimatun jadeedatun."},
                {"arabic": "نَحنُ نَلعَبُ فِی المَلعَبِ.", "farsi": "ما در زمین بازی، بازی می‌کنیم.", "english": "We play in the playground.", "english_pronunciation": "Nahnu nal'abu fil-mal'abi."},
                {"arabic": "الکِتابُ نَکرَةٌ.", "farsi": "کتاب نکره است.", "english": "The book is indefinite.", "english_pronunciation": "Al-kitabu nakiratun."},
                {"arabic": "هٰذَا الرَّجُلُ مَعرِفَةٌ.", "farsi": "این مرد معرفه است.", "english": "This man is definite.", "english_pronunciation": "Hadha ar-rajulu ma'rifatun."},
            ]
        },
        "lesson_2": {
            "words": [
                {"arabic": "تِکنولوجِیا", "farsi": "فناوری", "english": "Technology", "english_pronunciation": "Tiknooloojiyaa"},
                {"arabic": "حاسوب", "farsi": "رایانه", "english": "Computer", "english_pronunciation": "Haasoob"},
                {"arabic": "هاتِف", "farsi": "تلفن", "english": "Phone", "english_pronunciation": "Haatif"},
                {"arabic": "إنترنت", "farsi": "اینترنت", "english": "Internet", "english_pronunciation": "Intarnat"},
                {"arabic": "شاشَة", "farsi": "صفحه نمایش", "english": "Screen", "english_pronunciation": "Shaasha"},
                {"arabic": "بَرنامَج", "farsi": "برنامه", "english": "Program", "english_pronunciation": "Barnaamaj"},
                {"arabic": "مِلَف", "farsi": "پرونده", "english": "File", "english_pronunciation": "Milaf"},
                {"arabic": "مُتصَفِّح", "farsi": "مرورگر", "english": "Browser", "english_pronunciation": "Mutasaffih"},
                {"arabic": "شَبَکَة", "farsi": "شبکه", "english": "Network", "english_pronunciation": "Shabaka"},
                {"arabic": "رِسالَة", "farsi": "پیام", "english": "Message", "english_pronunciation": "Risaala"},
                {"arabic": "بَرید إلِکترونِی", "farsi": "ایمیل", "english": "Email", "english_pronunciation": "Bareed iliktronee"},
                {"arabic": "تَطبِیق", "farsi": "برنامه کاربردی", "english": "Application", "english_pronunciation": "Tatbeeq"},
                {"arabic": "جِهاز", "farsi": "دستگاه", "english": "Device", "english_pronunciation": "Jihaaz"},
                {"arabic": "شاحِن", "farsi": "شارژر", "english": "Charger", "english_pronunciation": "Shaahin"},
                {"arabic": "تَحدِیث", "farsi": "به‌روزرسانی", "english": "Update", "english_pronunciation": "Tahdeeth"},
            ],
            "sentences": [
                {"arabic": "التِّکنولوجِیا تُساعِدُ فِی التَّعلِیمِ.", "farsi": "فناوری به آموزش کمک می‌کند.", "english": "Technology helps in education.", "english_pronunciation": "At-tiknooloojiyaa tusa'idu fit-ta'leemi."},
                {"arabic": "أَستَخدِمُ الحاسوبَ کُلَّ یَومٍ.", "farsi": "هر روز از رایانه استفاده می‌کنم.", "english": "I use the computer every day.", "english_pronunciation": "Astakhdimu al-haasooba kulla yawmin."},
                {"arabic": "الهاتِفُ عَلى الشاشَةِ.", "farsi": "تلفن روی صفحه نمایش است.", "english": "The phone is on the screen.", "english_pronunciation": "Al-haatifu ala ash-shaashati."},
                {"arabic": "الإنترنتُ سَرِیعٌ.", "farsi": "اینترنت سریع است.", "english": "The internet is fast.", "english_pronunciation": "Al-intarnatu saree'un."},
                {"arabic": "أَفتَحُ مِلَفاً عَلى الحاسوبِ.", "farsi": "پرونده‌ای را روی رایانه باز می‌کنم.", "english": "I open a file on the computer.", "english_pronunciation": "Aftahu milafan ala al-haasoobi."},
                {"arabic": "أَرسَلْتُ رِسالَةً عَبْرَ البَریدِ الإلِکترونِی.", "farsi": "پیامی از طریق ایمیل فرستادم.", "english": "I sent a message via email.", "english_pronunciation": "Arsaltu risaalatan 'abra al-bareedi al-iliktronee."},
                {"arabic": "التَّطبِیقُ مُفِیدٌ جِدّاً.", "farsi": "برنامه کاربردی خیلی مفید است.", "english": "The application is very useful.", "english_pronunciation": "At-tatbeequ mufeedun jiddan."},
                {"arabic": "الشاحِنُ فِی الحَقِیبَةِ.", "farsi": "شارژر در کیف است.", "english": "The charger is in the bag.", "english_pronunciation": "Ash-shaahinu fil-haqeebati."},
            ]
        },
        "lesson_3": {
            "words": [
                {"arabic": "بِیئَة", "farsi": "محیط زیست", "english": "Environment", "english_pronunciation": "Bee'a"},
                {"arabic": "طَبِیعَة", "farsi": "طبیعت", "english": "Nature", "english_pronunciation": "Tabee'a"},
                {"arabic": "شَجَرَة", "farsi": "درخت", "english": "Tree", "english_pronunciation": "Shajara"},
                {"arabic": "نَهر", "farsi": "رودخانه", "english": "River", "english_pronunciation": "Nahr"},
                {"arabic": "جَبَل", "farsi": "کوه", "english": "Mountain", "english_pronunciation": "Jabal"},
                {"arabic": "غابَة", "farsi": "جنگل", "english": "Forest", "english_pronunciation": "Ghaaba"},
                {"arabic": "تَلَوُّث", "farsi": "آلودگی", "english": "Pollution", "english_pronunciation": "Talawwuth"},
                {"arabic": "هَواء", "farsi": "هوا", "english": "Air", "english_pronunciation": "Hawaa'"},
                {"arabic": "مِیاه", "farsi": "آب‌ها", "english": "Waters", "english_pronunciation": "Miyaah"},
                {"arabic": "حَیوان", "farsi": "حیوان", "english": "Animal", "english_pronunciation": "Hayawaan"},
                {"arabic": "نَبات", "farsi": "گیاه", "english": "Plant", "english_pronunciation": "Nabaat"},
                {"arabic": "حِمایَة", "farsi": "حفاظت", "english": "Protection", "english_pronunciation": "Himaaya"},
                {"arabic": "إِعادَة تَدوِیر", "farsi": "بازیافت", "english": "Recycling", "english_pronunciation": "I'aadat tadoor"},
                {"arabic": "نَظافَة", "farsi": "نظافت", "english": "Cleanliness", "english_pronunciation": "Nazaafa"},
                {"arabic": "تَوَعِیَة", "farsi": "آگاهی", "english": "Awareness", "english_pronunciation": "Taw'iya"},
            ],
            "sentences": [
                {"arabic": "البِیئَةُ نَظِیفَةٌ.", "farsi": "محیط زیست تمیز است.", "english": "The environment is clean.", "english_pronunciation": "Al-bee'atu nazeefatun."},
                {"arabic": "الطَّبِیعَةُ جَمِیلَةٌ فِی القَریَةِ.", "farsi": "طبیعت در روستا زیبا است.", "english": "Nature is beautiful in the village.", "english_pronunciation": "At-tabee'atu jameelatun fil-qaryati."},
                {"arabic": "نَزرَعُ شَجَرَةً فِی الحَدِیقَةِ.", "farsi": "درختی در باغ می‌کاریم.", "english": "We plant a tree in the garden.", "english_pronunciation": "Nazra'u shajaratan fil-hadeeqati."},
                {"arabic": "النَّهرُ یَجری بَینَ الجِبالِ.", "farsi": "رودخانه بین کوه‌ها جاری است.", "english": "The river flows between the mountains.", "english_pronunciation": "An-nahru yajree bayna al-jibaali."},
                {"arabic": "التَّلَوُّثُ یُؤذِی الحَیواناتِ.", "farsi": "آلودگی به حیوانات آسیب می‌رساند.", "english": "Pollution harms animals.", "english_pronunciation": "At-talawwuthu yu'dhee al-hayawanaati."},
                {"arabic": "نُحافِظُ عَلى نَظافَةِ الهَواءِ.", "farsi": "از پاکیزگی هوا محافظت می‌کنیم.", "english": "We preserve the cleanliness of the air.", "english_pronunciation": "Nuhaafidhu ala nazaafati al-hawaa'i."},
                {"arabic": "إِعادَةُ التَّدوِیرِ تُنقِذُ البِیئَةَ.", "farsi": "بازیافت محیط زیست را نجات می‌دهد.", "english": "Recycling saves the environment.", "english_pronunciation": "I'aadatu at-tadoori tunqidhu al-bee'ata."},
                {"arabic": "التَّوَعِیَةُ تُشَجِّعُ الحِمایَةَ.", "farsi": "آگاهی حفاظت را تشویق می‌کند.", "english": "Awareness encourages protection.", "english_pronunciation": "At-taw'iyatu tushajji'u al-himaayata."},
            ]
        },
        "lesson_4": {
            "words": [
                {"arabic": "ثَقافَة", "farsi": "فرهنگ", "english": "Culture", "english_pronunciation": "Thaqaafa"},
                {"arabic": "تُراث", "farsi": "میراث", "english": "Heritage", "english_pronunciation": "Turaath"},
                {"arabic": "تَقلِید", "farsi": "سنت", "english": "Tradition", "english_pronunciation": "Taqleed"},
                {"arabic": "فَن", "farsi": "هنر", "english": "Art", "english_pronunciation": "Fann"},
                {"arabic": "أَدَب", "farsi": "ادبیات", "english": "Literature", "english_pronunciation": "Adab"},
                {"arabic": "مَعرِض", "farsi": "نمایشگاه", "english": "Exhibition", "english_pronunciation": "Ma'rid"},
                {"arabic": "مَتحَف", "farsi": "موزه", "english": "Museum", "english_pronunciation": "Mathaf"},
                {"arabic": "مَسرَح", "farsi": "تئاتر", "english": "Theater", "english_pronunciation": "Masrah"},
                {"arabic": "موسِیقى", "farsi": "موسیقی", "english": "Music", "english_pronunciation": "Mooseeqaa"},
                {"arabic": "رَقص", "farsi": "رقص", "english": "Dance", "english_pronunciation": "Raqs"},
                {"arabic": "عِید", "farsi": "عید", "english": "Festival", "english_pronunciation": "Eid"},
                {"arabic": "مُجتَمَع", "farsi": "جامعه", "english": "Society", "english_pronunciation": "Mujtama'"},
                {"arabic": "تَعاوُن", "farsi": "همکاری", "english": "Cooperation", "english_pronunciation": "Ta'aawun"},
                {"arabic": "مُناسَبَة", "farsi": "مناسبت", "english": "Occasion", "english_pronunciation": "Munaasaba"},
                {"arabic": "هَوِیَّة", "farsi": "هویت", "english": "Identity", "english_pronunciation": "Hawiyya"},
            ],
            "sentences": [
                {"arabic": "الثَّقافَةُ تُقَوِّی الهَوِیَّةَ.", "farsi": "فرهنگ هویت را تقویت می‌کند.", "english": "Culture strengthens identity.", "english_pronunciation": "Ath-thaqaafatu tuqawwee al-hawiyyata."},
                {"arabic": "التُّراثُ یَحفَظُ التَّقالِیدَ.", "farsi": "میراث سنت‌ها را حفظ می‌کند.", "english": "Heritage preserves traditions.", "english_pronunciation": "At-turaathu yahfadhu at-taqaaleeda."},
                {"arabic": "الفَنُّ یَعبِّرُ عَنِ المُجتَمَعِ.", "farsi": "هنر از جامعه بیان می‌کند.", "english": "Art expresses society.", "english_pronunciation": "Al-fannu ya'bbiru an al-mujtama'i."},
                {"arabic": "أَزورُ المَتحَفَ فِی العِیدِ.", "farsi": "در عید به موزه می‌روم.", "english": "I visit the museum during the festival.", "english_pronunciation": "Azooru al-mathafa fil-eidi."},
                {"arabic": "المَسرَحُ یُقَدِّمُ عَرْضاً جَدِیداً.", "farsi": "تئاتر نمایش جدیدی ارائه می‌دهد.", "english": "The theater presents a new performance.", "english_pronunciation": "Al-masrahu yuqaddimu ardan jadeedan."},
                {"arabic": "الموسِیقى تُسعِدُ النَّاسَ.", "farsi": "موسیقی مردم را خوشحال می‌کند.", "english": "Music makes people happy.", "english_pronunciation": "Al-mooseeqaa tus'idu an-naasa."},
                {"arabic": "الرَّقصُ جُزءٌ مِنَ التَّقلِیدِ.", "farsi": "رقص بخشی از سنت است.", "english": "Dance is part of tradition.", "english_pronunciation": "Ar-raqsu juz'un mina at-taqleedi."},
                {"arabic": "التَّعاوُنُ یُعزِّزُ المُناسَبَةَ.", "farsi": "همکاری مناسبت را تقویت می‌کند.", "english": "Cooperation enhances the occasion.", "english_pronunciation": "At-ta'aawunu yu'azzizu al-munaasabata."},
            ]
        },
        "lesson_5": {
            "words": [
                {"arabic": "فَراغ", "farsi": "اوقات فراغت", "english": "Leisure", "english_pronunciation": "Faraagh"},
                {"arabic": "رِیاضَة", "farsi": "ورزش", "english": "Sport", "english_pronunciation": "Riyaada"},
                {"arabic": "سَفَر", "farsi": "سفر", "english": "Travel", "english_pronunciation": "Safar"},
                {"arabic": "قِراءَة", "farsi": "خواندن", "english": "Reading", "english_pronunciation": "Qiraa'a"},
                {"arabic": "رَسم", "farsi": "نقاشی", "english": "Drawing", "english_pronunciation": "Rasm"},
                {"arabic": "تَصوِیر", "farsi": "عکاسی", "english": "Photography", "english_pronunciation": "Tasweer"},
                {"arabic": "مُغامَرَة", "farsi": "ماجرا", "english": "Adventure", "english_pronunciation": "Mughaamara"},
                {"arabic": "لَعب", "farsi": "بازی", "english": "Game", "english_pronunciation": "La'b"},
                {"arabic": "فِلم", "farsi": "فیلم", "english": "Movie", "english_pronunciation": "Film"},
                {"arabic": "تِلْفاز", "farsi": "تلویزیون", "english": "Television", "english_pronunciation": "Tilfaaz"},
                {"arabic": "مُوسِیقى", "farsi": "موسیقی", "english": "Music", "english_pronunciation": "Mooseeqaa"},
                {"arabic": "تَخیِیم", "farsi": "کمپینگ", "english": "Camping", "english_pronunciation": "Takhyyeem"},
                {"arabic": "سِینَما", "farsi": "سینما", "english": "Cinema", "english_pronunciation": "Seenaama"},
                {"arabic": "مَجلَّة", "farsi": "مجله", "english": "Magazine", "english_pronunciation": "Majalla"},
                {"arabic": "هِوایَة", "farsi": "سرگرمی", "english": "Hobby", "english_pronunciation": "Hiwaaya"},
            ],
            "sentences": [
                {"arabic": "أَقضِی الفَراغَ فِی القِراءَةِ.", "farsi": "اوقات فراغتم را با خواندن می‌گذرانم.", "english": "I spend my leisure time reading.", "english_pronunciation": "Aqdee al-faraagha fil-qiraa'ati."},
                {"arabic": "الرِّیاضَةُ هِوایَتِی المُفَضَّلَةُ.", "farsi": "ورزش سرگرمی مورد علاقه من است.", "english": "Sport is my favorite hobby.", "english_pronunciation": "Ar-riyaadatu hiwaayatee al-mufaddalatu."},
                {"arabic": "أَسافِرُ فِی الصَّیفِ.", "farsi": "در تابستان سفر می‌کنم.", "english": "I travel in the summer.", "english_pronunciation": "Asaafiru fis-sayfi."},
                {"arabic": "أَرسُمُ فِی المَساءِ.", "farsi": "عصر نقاشی می‌کشم.", "english": "I draw in the evening.", "english_pronunciation": "Arsumu fil-masaa'i."},
                {"arabic": "التَّصوِیرُ یَجعَلُنِی سَعِیداً.", "farsi": "عکاسی مرا خوشحال می‌کند.", "english": "Photography makes me happy.", "english_pronunciation": "At-tasweeru yaj'alunee sa'eedan."},
                {"arabic": "المُغامَرَةُ مُمْتِعَةٌ.", "farsi": "ماجرا لذت‌بخش است.", "english": "Adventure is enjoyable.", "english_pronunciation": "Al-mughaamaratu mumti'atun."},
                {"arabic": "أَشاهِدُ فِلماً فِی السِّینَما.", "farsi": "فیلمی در سینما تماشا می‌کنم.", "english": "I watch a movie in the cinema.", "english_pronunciation": "Ashaahidu filman fis-seenaama."},
                {"arabic": "أَقرَأُ مَجلَّةً عَنِ التَّخیِیمِ.", "farsi": "مجله‌ای درباره کمپینگ می‌خوانم.", "english": "I read a magazine about camping.", "english_pronunciation": "Aqra'u majallatan an at-takhyyeemi."},
            ]
        },
        "lesson_6": {
            "words": [
                {"arabic": "تارِیخ", "farsi": "تاریخ", "english": "History", "english_pronunciation": "Taareekh"},
                {"arabic": "جُغرافیا", "farsi": "جغرافیا", "english": "Geography", "english_pronunciation": "Jughraafiyaa"},
                {"arabic": "مَدِینَة", "farsi": "شهر", "english": "City", "english_pronunciation": "Madeena"},
                {"arabic": "بَلَد", "farsi": "کشور", "english": "Country", "english_pronunciation": "Balad"},
                {"arabic": "عاصِمَة", "farsi": "پایتخت", "english": "Capital", "english_pronunciation": "Aasima"},
                {"arabic": "قارَّة", "farsi": "قاره", "english": "Continent", "english_pronunciation": "Qaarra"},
                {"arabic": "حَضارَة", "farsi": "تمدن", "english": "Civilization", "english_pronunciation": "Hadaara"},
                {"arabic": "مَملَکَة", "farsi": "پادشاهی", "english": "Kingdom", "english_pronunciation": "Mamlaka"},
                {"arabic": "حَرب", "farsi": "جنگ", "english": "War", "english_pronunciation": "Harb"},
                {"arabic": "سَلام", "farsi": "صلح", "english": "Peace", "english_pronunciation": "Salaam"},
                {"arabic": "مَلِک", "farsi": "پادشاه", "english": "King", "english_pronunciation": "Malik"},
                {"arabic": "شَعب", "farsi": "مردم", "english": "People", "english_pronunciation": "Sha'b"},
                {"arabic": "حُدود", "farsi": "مرز", "english": "Border", "english_pronunciation": "Hudood"},
                {"arabic": "خَرِیطَة", "farsi": "نقشه", "english": "Map", "english_pronunciation": "Khareeta"},
                {"arabic": "عَصر", "farsi": "عصر", "english": "Era", "english_pronunciation": "Asr"},
            ],
            "sentences": [
                {"arabic": "أَدرُسُ التّارِیخَ فِی المَدرَسَةِ.", "farsi": "تاریخ را در مدرسه می‌خوانم.", "english": "I study history in school.", "english_pronunciation": "Adrusu at-taareekha fil-madrasati."},
                {"arabic": "الجُغرافیا تَعرِفُ بِالبِلادِ.", "farsi": "جغرافیا کشورها را معرفی می‌کند.", "english": "Geography introduces countries.", "english_pronunciation": "Al-jughraafiyaa ta'rifu bil-bilaadi."},
                {"arabic": "العاصِمَةُ مَدِینَةٌ کَبِیرَةٌ.", "farsi": "پایتخت شهر بزرگی است.", "english": "The capital is a big city.", "english_pronunciation": "Al-aasimatu madeenatun kabeeratun."},
                {"arabic": "الحَضارَةُ الإسلامِیَّةُ قَدِیمَةٌ.", "farsi": "تمدن اسلامی قدیمی است.", "english": "Islamic civilization is ancient.", "english_pronunciation": "Al-hadaaratu al-islaamiyyatu qadeematun."},
                {"arabic": "المَلِکُ یَحکُمُ المَملَکَةَ.", "farsi": "پادشاه بر پادشاهی حکومت می‌کند.", "english": "The king rules the kingdom.", "english_pronunciation": "Al-maliku yahkumu al-mamlakata."},
                {"arabic": "السَّلامُ أَفضَلُ مِنَ الحَربِ.", "farsi": "صلح بهتر از جنگ است.", "english": "Peace is better than war.", "english_pronunciation": "As-salaamu afdalu mina al-harbi."},
                {"arabic": "الشَّعبُ یَعِیشُ فِی الحُدودِ.", "farsi": "مردم در مرزها زندگی می‌کنند.", "english": "The people live within the borders.", "english_pronunciation": "Ash-sha'bu ya'eeshu fil-hudoodi."},
                {"arabic": "أَنظُرُ إلى الخَرِیطَةِ.", "farsi": "به نقشه نگاه می‌کنم.", "english": "I look at the map.", "english_pronunciation": "Anzuru ila al-khareetati."},
            ]
        },
        "lesson_7": {
            "words": [
                {"arabic": "دِین", "farsi": "دین", "english": "Religion", "english_pronunciation": "Deen"},
                {"arabic": "إِیمان", "farsi": "ایمان", "english": "Faith", "english_pronunciation": "Eemaan"},
                {"arabic": "صَلاة", "farsi": "نماز", "english": "Prayer", "english_pronunciation": "Salaat"},
                {"arabic": "صَوم", "farsi": "روزه", "english": "Fasting", "english_pronunciation": "Sawm"},
                {"arabic": "زَکاة", "farsi": "زکات", "english": "Almsgiving", "english_pronunciation": "Zakaat"},
                {"arabic": "حَجّ", "farsi": "حج", "english": "Pilgrimage", "english_pronunciation": "Hajj"},
                {"arabic": "مَسجِد", "farsi": "مسجد", "english": "Mosque", "english_pronunciation": "Masjid"},
                {"arabic": "قُرآن", "farsi": "قرآن", "english": "Quran", "english_pronunciation": "Qur'aan"},
                {"arabic": "سُنَّة", "farsi": "سنت", "english": "Sunnah", "english_pronunciation": "Sunna"},
                {"arabic": "أَخلاق", "farsi": "اخلاق", "english": "Morals", "english_pronunciation": "Akhlaaq"},
                {"arabic": "تَعبُّد", "farsi": "عبادت", "english": "Worship", "english_pronunciation": "Ta'abbud"},
                {"arabic": "تَقوى", "farsi": "تقوا", "english": "Piety", "english_pronunciation": "Taqwa"},
                {"arabic": "دُعاء", "farsi": "دعا", "english": "Supplication", "english_pronunciation": "Du'aa"},
                {"arabic": "رَحمَة", "farsi": "رحمت", "english": "Mercy", "english_pronunciation": "Rahma"},
                {"arabic": "تَوبَة", "farsi": "توبه", "english": "Repentance", "english_pronunciation": "Tawba"},
            ],
            "sentences": [
                {"arabic": "الدِّینُ یُعَلِّمُ الأَخلاقَ.", "farsi": "دین اخلاق را می‌آموزد.", "english": "Religion teaches morals.", "english_pronunciation": "Ad-deenu yu'allimu al-akhlaaqa."},
                {"arabic": "الإِیمانُ فِی القلبِ.", "farsi": "ایمان در قلب است.", "english": "Faith is in the heart.", "english_pronunciation": "Al-eemaanu fil-qalbi."},
                {"arabic": "أُصَلِّی فِی المَسجِدِ.", "farsi": "در مسجد نماز می‌خوانم.", "english": "I pray in the mosque.", "english_pronunciation": "Usallee fil-masjidi."},
                {"arabic": "الصَّومُ فِی رَمَضانَ.", "farsi": "روزه در رمضان است.", "english": "Fasting is in Ramadan.", "english_pronunciation": "As-sawmu fi ramadaana."},
                {"arabic": "الزَّکاةُ تُساعِدُ الفُقَراءَ.", "farsi": "زکات به فقرا کمک می‌کند.", "english": "Almsgiving helps the poor.", "english_pronunciation": "Az-zakaatu tusa'idu al-fuqaraa'a."},
                {"arabic": "الحَجُّ فَرِیضَةٌ عَظِیمَةٌ.", "farsi": "حج فریضه بزرگی است.", "english": "Pilgrimage is a great obligation.", "english_pronunciation": "Al-hajju fareedatun 'azeematun."},
                {"arabic": "أَقرَأُ القُرآنَ کُلَّ یَومٍ.", "farsi": "هر روز قرآن می‌خوانم.", "english": "I read the Quran every day.", "english_pronunciation": "Aqra'u al-qur'aana kulla yawmin."},
                {"arabic": "التَّقوى تَقِی مِنَ الذُّنوبِ.", "farsi": "تقوا از گناهان محافظت می‌کند.", "english": "Piety protects from sins.", "english_pronunciation": "At-taqwa taqee mina adh-dhunoobi."},
            ]
        },
        "lesson_8": {
            "words": [
                {"arabic": "مُحادَثَة", "farsi": "مکالمه", "english": "Conversation", "english_pronunciation": "Muhaadatha"},
                {"arabic": "سَلامَة", "farsi": "سلامتی", "english": "Safety", "english_pronunciation": "Salaama"},
                {"arabic": "سُؤال", "farsi": "سوال", "english": "Question", "english_pronunciation": "Su'aal"},
                {"arabic": "جَواب", "farsi": "جواب", "english": "Answer", "english_pronunciation": "Jawaab"},
                {"arabic": "مَوضوع", "farsi": "موضوع", "english": "Topic", "english_pronunciation": "Mawdoo'"},
                {"arabic": "رَأی", "farsi": "نظر", "english": "Opinion", "english_pronunciation": "Ra'y"},
                {"arabic": "نِقاش", "farsi": "بحث", "english": "Discussion", "english_pronunciation": "Niqaash"},
                {"arabic": "اِتِّفاق", "farsi": "توافق", "english": "Agreement", "english_pronunciation": "Ittifaaq"},
                {"arabic": "اِختِلاف", "farsi": "اختلاف", "english": "Disagreement", "english_pronunciation": "Ikhtilaaf"},
                {"arabic": "مُشارَکَة", "farsi": "مشارکت", "english": "Participation", "english_pronunciation": "Mushaarakah"},
                {"arabic": "صَدِیق", "farsi": "دوست (مرد)", "english": "Friend (male)", "english_pronunciation": "Sadeeq"},
                {"arabic": "صَدِیقَة", "farsi": "دوست (زن)", "english": "Friend (female)", "english_pronunciation": "Sadeeqa"},
                {"arabic": "لِقاء", "farsi": "ملاقات", "english": "Meeting", "english_pronunciation": "Liqaa'"},
                {"arabic": "تَواصُل", "farsi": "ارتباط", "english": "Communication", "english_pronunciation": "Tawaasul"},
                {"arabic": "حِوار", "farsi": "گفت‌وگو", "english": "Dialogue", "english_pronunciation": "Hiwaar"},
            ],
            "sentences": [
                {"arabic": "المُحادَثَةُ مَعَ الصَّدِیقِ مُمْتِعَةٌ.", "farsi": "مکالمه با دوست لذت‌بخش است.", "english": "Conversation with a friend is enjoyable.", "english_pronunciation": "Al-muhaadathatu ma'a as-sadeeqi mumti'atun."},
                {"arabic": "أَسأَلُ سُؤالاً عَنِ المَوضوعِ.", "farsi": "سوالی درباره موضوع می‌پرسم.", "english": "I ask a question about the topic.", "english_pronunciation": "As'alu su'aalan an al-mawdoo'i."},
                {"arabic": "الجَوابُ واضِحٌ.", "farsi": "جواب روشن است.", "english": "The answer is clear.", "english_pronunciation": "Al-jawaabu waadihun."},
                {"arabic": "النِّقاشُ یُؤدِّی إلى الاِتِّفاقِ.", "farsi": "بحث به توافق منجر می‌شود.", "english": "Discussion leads to agreement.", "english_pronunciation": "An-niqaashu yu'uddee ila al-ittifaaqi."},
                {"arabic": "الاِختِلافُ فِی الرَّأیِ طَبِیعِیٌّ.", "farsi": "اختلاف نظر طبیعی است.", "english": "Disagreement in opinion is natural.", "english_pronunciation": "Al-ikhtilaafu fir-ra'yi tabee'iyyun."},
                {"arabic": "المُشارَکَةُ فِی الحِوارِ مُهِمَّةٌ.", "farsi": "مشارکت در گفت‌وگو مهم است.", "english": "Participation in dialogue is important.", "english_pronunciation": "Al-mushaarakatu fil-hiwaari muhimmatun."},
                {"arabic": "اللِّقاءُ مَعَ الصَّدِیقَةِ اليَومَ.", "farsi": "ملاقات با دوست (زن) امروز است.", "english": "The meeting with the friend (female) is today.", "english_pronunciation": "Al-liqaa'u ma'a as-sadeeqati al-yawma."},
                {"arabic": "التَّواصُلُ یُقَرِّبُ النَّاسَ.", "farsi": "ارتباط مردم را به هم نزدیک می‌کند.", "english": "Communication brings people closer.", "english_pronunciation": "At-tawaasulu yuqarribu an-naasa."},
            ]
        }
    }

}