# FILE: english_data.py

ENGLISH_DATA = {

    "7th_grade": {
        "lesson_1": {
            "words": [
                {"english": "Book", "farsi": "کتاب", "arabic": "کِتاب", "pronunciation": "/bʊk/"},
                {"english": "Pen", "farsi": "خودکار", "arabic": "قَلَم", "pronunciation": "/pɛn/"},
                {"english": "Teacher", "farsi": "معلم", "arabic": "مُعَلِّم", "pronunciation": "/ˈtiː.tʃər/"},
                {"english": "Student", "farsi": "دانش‌آموز", "arabic": "تِلمیذ", "pronunciation": "/ˈstjuː.dənt/"},
                {"english": "Classroom", "farsi": "کلاس درس", "arabic": "صَفّ", "pronunciation": "/ˈklæs.ruːm/"},
                {"english": "Hello", "farsi": "سلام", "arabic": "مَرحَباً", "pronunciation": "/həˈloʊ/"},
                {"english": "Goodbye", "farsi": "خداحافظ", "arabic": "وَدَاعاً", "pronunciation": "/ɡʊdˈbaɪ/"},
                {"english": "Name", "farsi": "نام", "arabic": "اِسم", "pronunciation": "/neɪm/"},
                {"english": "School", "farsi": "مدرسه", "arabic": "مَدرَسَة", "pronunciation": "/skuːl/"},
                {"english": "Friend", "farsi": "دوست", "arabic": "صَدِیق", "pronunciation": "/frɛnd/"},
            ],
            "sentences": [
                {"english": "This is a book.", "farsi": "این یک کتاب است.", "arabic": "هذا کِتابٌ."},
                {"english": "What is your name?", "farsi": "نام شما چیست؟", "arabic": "ما اسمُکَ؟"},
                {"english": "The teacher is in the classroom.", "farsi": "معلم در کلاس است.",
                 "arabic": "اَلمُعَلِّمُ فِی الصَّفِّ."},
                {"english": "Goodbye, student.", "farsi": "خداحافظ، دانش‌آموز.",
                 "arabic": "وَدَاعاً أَیُّهَا التِّلمیذُ."},
                {"english": "My friend is at school.", "farsi": "دوست من در مدرسه است.",
                 "arabic": "صَدِیقِی فِی المَدرَسَةِ."},
            ]
        },
        "lesson_2": {
            "words": [
                {"english": "Family", "farsi": "خانواده", "arabic": "عائِلَة", "pronunciation": "/ˈfæm.əl.i/"},
                {"english": "Father", "farsi": "پدر", "arabic": "أَب", "pronunciation": "/ˈfɑː.ðər/"},
                {"english": "Mother", "farsi": "مادر", "arabic": "أُمّ", "pronunciation": "/ˈmʌð.ər/"},
                {"english": "Brother", "farsi": "برادر", "arabic": "أَخ", "pronunciation": "/ˈbrʌð.ər/"},
                {"english": "Sister", "farsi": "خواهر", "arabic": "أُخت", "pronunciation": "/ˈsɪs.tər/"},
                {"english": "Doctor", "farsi": "پزشک", "arabic": "طَبِیب", "pronunciation": "/ˈdɒk.tər/"},
                {"english": "Nurse", "farsi": "پرستار", "arabic": "مُمَرِّضَة", "pronunciation": "/nɜːrs/"},
                {"english": "House", "farsi": "خانه", "arabic": "بَیت", "pronunciation": "/haʊs/"},
                {"english": "Home", "farsi": "خانه", "arabic": "مَنزِل", "pronunciation": "/hoʊm/"},
            ],
            "sentences": [
                {"english": "My father is a doctor.", "farsi": "پدر من یک پزشک است.", "arabic": "أَبي طَبِیبٌ."},
                {"english": "My mother is a nurse.", "farsi": "مادر من یک پرستار است.", "arabic": "أُمّي مُمَرِّضَةٌ."},
                {"english": "I have one brother and two sisters.", "farsi": "من یک برادر و دو خواهر دارم.",
                 "arabic": "لَدَیَّ أَخٌ واحِدٌ وأُختانِ."},
                {"english": "Our family lives in a big house.", "farsi": "خانواده ما در خانه بزرگی زندگی می‌کند.",
                 "arabic": "عائِلَتُنا تَعِیشُ فِی بَیتٍ کَبِیرٍ."},
                {"english": "This is my home.", "farsi": "این خانه من است.", "arabic": "هذا مَنزِلِی."},
            ]
        },
        "lesson_3": {
            "words": [
                {"english": "One", "farsi": "یک", "arabic": "واحِد", "pronunciation": "/wʌn/"},
                {"english": "Two", "farsi": "دو", "arabic": "اِثنان", "pronunciation": "/tuː/"},
                {"english": "Three", "farsi": "سه", "arabic": "ثَلاثَة", "pronunciation": "/θriː/"},
                {"english": "Four", "farsi": "چهار", "arabic": "أَربَعَة", "pronunciation": "/fɔːr/"},
                {"english": "Five", "farsi": "پنج", "arabic": "خَمسَة", "pronunciation": "/faɪv/"},
                {"english": "Six", "farsi": "شش", "arabic": "سِتَّة", "pronunciation": "/sɪks/"},
                {"english": "Seven", "farsi": "هفت", "arabic": "سَبعَة", "pronunciation": "/ˈsɛv.ən/"},
                {"english": "Eight", "farsi": "هشت", "arabic": "ثَمانِیَة", "pronunciation": "/eɪt/"},
                {"english": "Number", "farsi": "عدد", "arabic": "رَقَم", "pronunciation": "/ˈnʌm.bər/"},
                {"english": "Count", "farsi": "شمردن", "arabic": "عَدّ", "pronunciation": "/kaʊnt/"},
            ],
            "sentences": [
                {"english": "I have two books.", "farsi": "من دو کتاب دارم.", "arabic": "لَدَیَّ کِتابانِ."},
                {"english": "There are five students in the classroom.", "farsi": "پنج دانش‌آموز در کلاس هستند.",
                 "arabic": "یوجَدُ خَمسَةُ تَلامِیذَ فِی الصَّفِّ."},
                {"english": "Count from one to eight.", "farsi": "از یک تا هشت بشمار.",
                 "arabic": "عُدَّ مِن واحِدٍ إلى ثَمانِیَةٍ."},
                {"english": "Three is my favorite number.", "farsi": "سه عدد مورد علاقه من است.",
                 "arabic": "ثَلاثَةٌ رَقَمِی المُفَضَّلُ."},
                {"english": "She has four pens.", "farsi": "او چهار خودکار دارد.",
                 "arabic": "لَدَیها أَربَعَةُ أَقلامٍ."},
            ]
        },
        "lesson_4": {
            "words": [
                {"english": "Red", "farsi": "قرمز", "arabic": "أَحمَر", "pronunciation": "/rɛd/"},
                {"english": "Blue", "farsi": "آبی", "arabic": "أَزرَق", "pronunciation": "/bluː/"},
                {"english": "Green", "farsi": "سبز", "arabic": "أَخضَر", "pronunciation": "/ɡriːn/"},
                {"english": "Yellow", "farsi": "زرد", "arabic": "أَصفَر", "pronunciation": "/ˈjɛl.oʊ/"},
                {"english": "Black", "farsi": "سیاه", "arabic": "أَسوَد", "pronunciation": "/blæk/"},
                {"english": "White", "farsi": "سفید", "arabic": "أَبیَض", "pronunciation": "/waɪt/"},
                {"english": "Color", "farsi": "رنگ", "arabic": "لَون", "pronunciation": "/ˈkʌl.ər/"},
                {"english": "Bag", "farsi": "کیف", "arabic": "حَقِیبَة", "pronunciation": "/bæɡ/"},
                {"english": "Shirt", "farsi": "پیراهن", "arabic": "قَمِیص", "pronunciation": "/ʃɜːrt/"},
            ],
            "sentences": [
                {"english": "My bag is red.", "farsi": "کیف من قرمز است.", "arabic": "حَقِیبَتِی حَمراءُ."},
                {"english": "The shirt is blue.", "farsi": "پیراهن آبی است.", "arabic": "القَمِیصُ أَزرَقُ."},
                {"english": "I like the green color.", "farsi": "من رنگ سبز را دوست دارم.",
                 "arabic": "أُحِبُّ اللَّونَ الأَخضَرَ."},
                {"english": "Her book is yellow.", "farsi": "کتاب او زرد است.", "arabic": "کِتابُها أَصفَرُ."},
                {"english": "The pen is black.", "farsi": "خودکار سیاه است.", "arabic": "القَلَمُ أَسوَدُ."},
            ]
        },
        "lesson_5": {
            "words": [
                {"english": "Cat", "farsi": "گربه", "arabic": "قِطّ", "pronunciation": "/kæt/"},
                {"english": "Dog", "farsi": "سگ", "arabic": "کَلب", "pronunciation": "/dɒɡ/"},
                {"english": "Bird", "farsi": "پرنده", "arabic": "طَیر", "pronunciation": "/bɜːrd/"},
                {"english": "Fish", "farsi": "ماهی", "arabic": "سَمَکَة", "pronunciation": "/fɪʃ/"},
                {"english": "Horse", "farsi": "اسب", "arabic": "حِصان", "pronunciation": "/hɔːrs/"},
                {"english": "Animal", "farsi": "حیوان", "arabic": "حَیَوان", "pronunciation": "/ˈæn.ɪ.məl/"},
                {"english": "Pet", "farsi": "حیوان خانگی", "arabic": "حَیَوانٌ أَلِیف", "pronunciation": "/pɛt/"},
                {"english": "Garden", "farsi": "باغ", "arabic": "حَدِیقَة", "pronunciation": "/ˈɡɑːr.dən/"},
                {"english": "Home", "farsi": "خانه", "arabic": "مَنزِل", "pronunciation": "/hoʊm/"},
            ],
            "sentences": [
                {"english": "The cat is in the garden.", "farsi": "گربه در باغ است.",
                 "arabic": "القِطُّ فِی الحَدِیقَةِ."},
                {"english": "My dog is my pet.", "farsi": "سگ من حیوان خانگی من است.",
                 "arabic": "کَلبِی هُوَ حَیَوانِی الأَلِیفُ."},
                {"english": "The bird is on the tree.", "farsi": "پرنده روی درخت است.",
                 "arabic": "الطَّیرُ عَلى الشَّجَرَةِ."},
                {"english": "I have a fish at home.", "farsi": "من در خانه یک ماهی دارم.",
                 "arabic": "لَدَیَّ سَمَکَةٌ فِی المَنزِلِ."},
                {"english": "The horse runs fast.", "farsi": "اسب سریع می‌دود.", "arabic": "الحِصانُ یَجرِی سَرِیعاً."},
            ]
        },
        "lesson_6": {
            "words": [
                {"english": "Food", "farsi": "غذا", "arabic": "طَعام", "pronunciation": "/fuːd/"},
                {"english": "Bread", "farsi": "نان", "arabic": "خُبز", "pronunciation": "/brɛd/"},
                {"english": "Rice", "farsi": "برنج", "arabic": "أَرُزّ", "pronunciation": "/raɪs/"},
                {"english": "Water", "farsi": "آب", "arabic": "ماء", "pronunciation": "/ˈwɔː.tər/"},
                {"english": "Milk", "farsi": "شیر", "arabic": "حَلِیب", "pronunciation": "/mɪlk/"},
                {"english": "Apple", "farsi": "سیب", "arabic": "تُفّاحَة", "pronunciation": "/ˈæp.əl/"},
                {"english": "Orange", "farsi": "پرتقال", "arabic": "بُرتُقالَة", "pronunciation": "/ˈɒr.ɪndʒ/"},
                {"english": "Eat", "farsi": "خوردن", "arabic": "أَکَلَ", "pronunciation": "/iːt/"},
                {"english": "Drink", "farsi": "نوشیدن", "arabic": "شَرِبَ", "pronunciation": "/drɪŋk/"},
            ],
            "sentences": [
                {"english": "I eat bread and rice.", "farsi": "من نان و برنج می‌خورم.",
                 "arabic": "آکُلُ الخُبزَ والأَرُزَّ."},
                {"english": "She drinks water.", "farsi": "او آب می‌نوشد.", "arabic": "هِیَ تَشرَبُ الماءَ."},
                {"english": "The apple is red.", "farsi": "سیب قرمز است.", "arabic": "التُّفّاحَةُ حَمراءُ."},
                {"english": "My brother likes milk.", "farsi": "برادرم شیر دوست دارد.",
                 "arabic": "أَخِی یُحِبُّ الحَلِیبَ."},
                {"english": "We have oranges at home.", "farsi": "ما در خانه پرتقال داریم.",
                 "arabic": "لَدَینا بُرتُقالَاتٌ فِی المَنزِلِ."},
            ]
        },
        "lesson_7": {
            "words": [
                {"english": "Morning", "farsi": "صبح", "arabic": "صَباح", "pronunciation": "/ˈmɔːr.nɪŋ/"},
                {"english": "Evening", "farsi": "عصر", "arabic": "مَساء", "pronunciation": "/ˈiːv.nɪŋ/"},
                {"english": "Day", "farsi": "روز", "arabic": "یَوم", "pronunciation": "/deɪ/"},
                {"english": "Night", "farsi": "شب", "arabic": "لَیل", "pronunciation": "/naɪt/"},
                {"english": "School", "farsi": "مدرسه", "arabic": "مَدرَسَة", "pronunciation": "/skuːl/"},
                {"english": "Play", "farsi": "بازی کردن", "arabic": "لَعِبَ", "pronunciation": "/pleɪ/"},
                {"english": "Sleep", "farsi": "خوابیدن", "arabic": "نامَ", "pronunciation": "/sliːp/"},
                {"english": "Study", "farsi": "درس خواندن", "arabic": "دَرَسَ", "pronunciation": "/ˈstʌd.i/"},
                {"english": "Time", "farsi": "زمان", "arabic": "زَمان", "pronunciation": "/taɪm/"},
            ],
            "sentences": [
                {"english": "I go to school in the morning.", "farsi": "من صبح به مدرسه می‌روم.",
                 "arabic": "أَذهَبُ إلى المَدرَسَةِ صَباحاً."},
                {"english": "We play in the evening.", "farsi": "ما عصر بازی می‌کنیم.", "arabic": "نَلعَبُ مَساءً."},
                {"english": "I sleep at night.", "farsi": "من شب می‌خوابم.", "arabic": "أَنامُ لَیلاً."},
                {"english": "She studies every day.", "farsi": "او هر روز درس می‌خواند.",
                 "arabic": "هِیَ تَدرُسُ کُلَّ یَومٍ."},
                {"english": "What time is it?", "farsi": "ساعت چند است؟", "arabic": "کَمِ السَّاعَةُ؟"},
            ]
        },
        "lesson_8": {
            "words": [
                {"english": "City", "farsi": "شهر", "arabic": "مَدِینَة", "pronunciation": "/ˈsɪt.i/"},
                {"english": "Village", "farsi": "روستا", "arabic": "قَریَة", "pronunciation": "/ˈvɪl.ɪdʒ/"},
                {"english": "Street", "farsi": "خیابان", "arabic": "شارِع", "pronunciation": "/striːt/"},
                {"english": "Market", "farsi": "بازار", "arabic": "سُوق", "pronunciation": "/ˈmɑːr.kɪt/"},
                {"english": "Park", "farsi": "پارک", "arabic": "حَدِیقَة", "pronunciation": "/pɑːrk/"},
                {"english": "Shop", "farsi": "فروشگاه", "arabic": "مَتجَر", "pronunciation": "/ʃɒp/"},
                {"english": "Home", "farsi": "خانه", "arabic": "مَنزِل", "pronunciation": "/hoʊm/"},
                {"english": "Place", "farsi": "مکان", "arabic": "مَکان", "pronunciation": "/pleɪs/"},
                {"english": "Go", "farsi": "رفتن", "arabic": "ذَهَبَ", "pronunciation": "/ɡoʊ/"},
            ],
            "sentences": [
                {"english": "I live in a city.", "farsi": "من در شهر زندگی می‌کنم.",
                 "arabic": "أَعِیشُ فِی مَدِینَةٍ."},
                {"english": "The market is in the village.", "farsi": "بازار در روستا است.",
                 "arabic": "السُّوقُ فِی القَریَةِ."},
                {"english": "We go to the park.", "farsi": "ما به پارک می‌رویم.", "arabic": "نَذهَبُ إلى الحَدِیقَةِ."},
                {"english": "The shop is on the street.", "farsi": "فروشگاه در خیابان است.",
                 "arabic": "المَتجَرُ فِی الشارِعِ."},
                {"english": "This is a nice place.", "farsi": "این مکان خوبی است.", "arabic": "هذا مَکانٌ جَمِیلٌ."},
            ]
        }
    },

    "8th_grade": {
        "lesson_1": {
            "words": [
                {"english": "Tall", "farsi": "بلند قد", "arabic": "طَوِیل", "pronunciation": "/tɔːl/"},
                {"english": "Short", "farsi": "کوتاه قد", "arabic": "قَصِیر", "pronunciation": "/ʃɔːrt/"},
                {"english": "Young", "farsi": "جوان", "arabic": "شابّ", "pronunciation": "/jʌŋ/"},
                {"english": "Old", "farsi": "پیر", "arabic": "عَجُوز", "pronunciation": "/oʊld/"},
                {"english": "Kind", "farsi": "مهربان", "arabic": "لَطِیف", "pronunciation": "/kaɪnd/"},
                {"english": "Friendly", "farsi": "دوستانه", "arabic": "وَدُود", "pronunciation": "/ˈfrɛnd.li/"},
                {"english": "Hair", "farsi": "مو", "arabic": "شَعر", "pronunciation": "/hɛər/"},
                {"english": "Eye", "farsi": "چشم", "arabic": "عَین", "pronunciation": "/aɪ/"},
                {"english": "Beautiful", "farsi": "زیبا", "arabic": "جَمِیل", "pronunciation": "/ˈbjuː.tɪ.fəl/"},
                {"english": "Appearance", "farsi": "ظاهر", "arabic": "مَظهَر", "pronunciation": "/əˈpɪr.əns/"},
                {"english": "Smart", "farsi": "باهوش", "arabic": "ذَکِی", "pronunciation": "/smɑːrt/"},
                {"english": "Funny", "farsi": "خنده‌دار", "arabic": "مُضحِک", "pronunciation": "/ˈfʌn.i/"},
                {"english": "Serious", "farsi": "جدی", "arabic": "جَدِّی", "pronunciation": "/ˈsɪər.i.əs/"},
                {"english": "Personality", "farsi": "شخصیت", "arabic": "شَخصِیَّة",
                 "pronunciation": "/ˌpɜːr.səˈnæl.ɪ.ti/"},
            ],
            "sentences": [
                {"english": "She is tall and kind.", "farsi": "او بلند قد و مهربان است.",
                 "arabic": "هِیَ طَوِیلَةٌ وَلَطِیفَةٌ."},
                {"english": "My friend has short hair.", "farsi": "دوست من موهای کوتاه دارد.",
                 "arabic": "صَدِیقِی لَهُ شَعرٌ قَصِیرٌ."},
                {"english": "He is a young and friendly boy.", "farsi": "او پسری جوان و دوستانه است.",
                 "arabic": "هُوَ شابٌّ وَدُودٌ."},
                {"english": "Her eyes are beautiful.", "farsi": "چشمان او زیبا هستند.",
                 "arabic": "عَیناها جَمِیلَتانِ."},
                {"english": "Appearance is not everything.", "farsi": "ظاهر همه چیز نیست.",
                 "arabic": "المَظهَرُ لَیسَ کُلُّ شَیءٍ."},
                {"english": "My brother is smart and funny.", "farsi": "برادرم باهوش و خنده‌دار است.",
                 "arabic": "أَخِی ذَکِیٌّ وَمُضحِکٌ."},
                {"english": "She has a serious personality.", "farsi": "او شخصیت جدی دارد.",
                 "arabic": "لَها شَخصِیَّةٌ جَدِّیَّةٌ."},
                {"english": "He looks old but is very kind.", "farsi": "او پیر به نظر می‌رسد اما بسیار مهربان است.",
                 "arabic": "یَبدُو عَجُوزاً لٰکِنَّهُ لَطِیفٌ جِدّاً."},
            ]
        },
        "lesson_2": {
            "words": [
                {"english": "Job", "farsi": "شغل", "arabic": "وَظِیفَة", "pronunciation": "/dʒɒb/"},
                {"english": "Doctor", "farsi": "پزشک", "arabic": "طَبِیب", "pronunciation": "/ˈdɒk.tər/"},
                {"english": "Teacher", "farsi": "معلم", "arabic": "مُعَلِّم", "pronunciation": "/ˈtiː.tʃər/"},
                {"english": "Engineer", "farsi": "مهندس", "arabic": "مُهَندِس", "pronunciation": "/ˌɛn.dʒɪˈnɪr/"},
                {"english": "Farmer", "farsi": "کشاورز", "arabic": "مُزارِع", "pronunciation": "/ˈfɑːr.mər/"},
                {"english": "Office", "farsi": "دفتر", "arabic": "مَکتَب", "pronunciation": "/ˈɒf.ɪs/"},
                {"english": "Work", "farsi": "کار", "arabic": "عَمَل", "pronunciation": "/wɜːrk/"},
                {"english": "Busy", "farsi": "مشغول", "arabic": "مَشغول", "pronunciation": "/ˈbɪz.i/"},
                {"english": "Help", "farsi": "کمک", "arabic": "مُساعَدَة", "pronunciation": "/hɛlp/"},
                {"english": "Lawyer", "farsi": "وکیل", "arabic": "مُحامٍ", "pronunciation": "/ˈlɔː.jər/"},
                {"english": "Nurse", "farsi": "پرستار", "arabic": "مُمَرِّضَة", "pronunciation": "/nɜːrs/"},
                {"english": "Worker", "farsi": "کارگر", "arabic": "عامِل", "pronunciation": "/ˈwɜːr.kər/"},
                {"english": "Profession", "farsi": "حرفه", "arabic": "مِهنَة", "pronunciation": "/prəˈfɛʃ.ən/"},
            ],
            "sentences": [
                {"english": "My father is a doctor.", "farsi": "پدرم پزشک است.", "arabic": "أَبي طَبِیبٌ."},
                {"english": "The teacher works in an office.", "farsi": "معلم در دفتر کار می‌کند.",
                 "arabic": "المُعَلِّمُ یَعمَلُ فِی مَکتَبٍ."},
                {"english": "The farmer is busy.", "farsi": "کشاورز مشغول است.", "arabic": "المُزارِعُ مَشغولٌ."},
                {"english": "Engineers help build houses.", "farsi": "مهندسان به ساخت خانه‌ها کمک می‌کنند.",
                 "arabic": "المُهَندِسونَ یُساعِدونَ فِی بِناءِ البُیوتِ."},
                {"english": "I want to be a lawyer.", "farsi": "می‌خواهم وکیل شوم.",
                 "arabic": "أُرِیدُ أَن أَکونَ مُحامِیاً."},
                {"english": "The nurse helps the patients.", "farsi": "پرستار به بیماران کمک می‌کند.",
                 "arabic": "المُمَرِّضَةُ تُساعِدُ المَرضی."},
                {"english": "This profession is interesting.", "farsi": "این حرفه جالب است.",
                 "arabic": "هٰذِهِ المِهنَةُ مُثِیرَةٌ."},
                {"english": "Workers are in the office.", "farsi": "کارگران در دفتر هستند.",
                 "arabic": "العُمّالُ فِی المَکتَبِ."},
            ]
        },
        "lesson_3": {
            "words": [
                {"english": "Time", "farsi": "زمان", "arabic": "زَمان", "pronunciation": "/taɪm/"},
                {"english": "Morning", "farsi": "صبح", "arabic": "صَباح", "pronunciation": "/ˈmɔːr.nɪŋ/"},
                {"english": "Afternoon", "farsi": "بعدازظهر", "arabic": "بَعدَ الظُّهر",
                 "pronunciation": "/ˌæf.tərˈnuːn/"},
                {"english": "Evening", "farsi": "عصر", "arabic": "مَساء", "pronunciation": "/ˈiːv.nɪŋ/"},
                {"english": "Night", "farsi": "شب", "arabic": "لَیل", "pronunciation": "/naɪt/"},
                {"english": "Clock", "farsi": "ساعت", "arabic": "ساعَة", "pronunciation": "/klɒk/"},
                {"english": "Schedule", "farsi": "برنامه", "arabic": "جَدول", "pronunciation": "/ˈskɛdʒ.uːl/"},
                {"english": "Wake up", "farsi": "بیدار شدن", "arabic": "اِستَیقَظَ", "pronunciation": "/weɪk ʌp/"},
                {"english": "Sleep", "farsi": "خوابیدن", "arabic": "نامَ", "pronunciation": "/sliːp/"},
                {"english": "Study", "farsi": "درس خواندن", "arabic": "دَرَسَ", "pronunciation": "/ˈstʌd.i/"},
                {"english": "Rest", "farsi": "استراحت", "arabic": "راحَة", "pronunciation": "/rɛst/"},
                {"english": "Hour", "farsi": "ساعت", "arabic": "ساعَة", "pronunciation": "/aʊər/"},
                {"english": "Minute", "farsi": "دقیقه", "arabic": "دَقِیقَة", "pronunciation": "/ˈmɪn.ɪt/"},
                {"english": "Day", "farsi": "روز", "arabic": "یَوم", "pronunciation": "/deɪ/"},
            ],
            "sentences": [
                {"english": "I wake up at seven in the morning.", "farsi": "من ساعت هفت صبح بیدار می‌شوم.",
                 "arabic": "أَستَیقِظُ فِی السَّاعَةِ السَّابِعَةِ صَباحاً."},
                {"english": "She studies in the afternoon.", "farsi": "او بعدازظهر درس می‌خواند.",
                 "arabic": "هِیَ تَدرُسُ بَعدَ الظُّهرِ."},
                {"english": "The clock is on the wall.", "farsi": "ساعت روی دیوار است.",
                 "arabic": "السَّاعَةُ عَلى الحائِطِ."},
                {"english": "We rest in the evening.", "farsi": "ما عصر استراحت می‌کنیم.", "arabic": "نَرتاحُ مَساءً."},
                {"english": "My schedule is busy today.", "farsi": "برنامه من امروز شلوغ است.",
                 "arabic": "جَدولِی مَشغولٌ الیَومَ."},
                {"english": "I sleep for eight hours at night.", "farsi": "من شب هشت ساعت می‌خوابم.",
                 "arabic": "أَنامُ لِثَمانِی ساعاتٍ لَیلاً."},
                {"english": "The lesson starts in ten minutes.", "farsi": "درس ده دقیقه دیگر شروع می‌شود.",
                 "arabic": "الدَّرسُ یَبدَأُ بَعدَ عَشرَ دَقائِقَ."},
                {"english": "It is a busy day.", "farsi": "امروز روز شلوغی است.", "arabic": "هُوَ یَومٌ مَشغولٌ."},
            ]
        },
        "lesson_4": {
            "words": [
                {"english": "Shop", "farsi": "فروشگاه", "arabic": "مَتجَر", "pronunciation": "/ʃɒp/"},
                {"english": "Buy", "farsi": "خریدن", "arabic": "اِشتَرى", "pronunciation": "/baɪ/"},
                {"english": "Sell", "farsi": "فروختن", "arabic": "باعَ", "pronunciation": "/sɛl/"},
                {"english": "Market", "farsi": "بازار", "arabic": "سُوق", "pronunciation": "/ˈmɑːr.kɪt/"},
                {"english": "Money", "farsi": "پول", "arabic": "نُقود", "pronunciation": "/ˈmʌn.i/"},
                {"english": "Price", "farsi": "قیمت", "arabic": "سِعر", "pronunciation": "/praɪs/"},
                {"english": "Clothes", "farsi": "لباس", "arabic": "مَلابِس", "pronunciation": "/kloʊðz/"},
                {"english": "Shoes", "farsi": "کفش", "arabic": "جَزْمَة", "pronunciation": "/ʃuːz/"},
                {"english": "Bag", "farsi": "کیف", "arabic": "حَقِیبَة", "pronunciation": "/bæɡ/"},
                {"english": "Store", "farsi": "فروشگاه", "arabic": "مَخزَن", "pronunciation": "/stɔːr/"},
                {"english": "Cheap", "farsi": "ارزان", "arabic": "رَخِیص", "pronunciation": "/tʃiːp/"},
                {"english": "Expensive", "farsi": "گران", "arabic": "غالٍ", "pronunciation": "/ɪkˈspɛn.sɪv/"},
                {"english": "Pay", "farsi": "پرداخت کردن", "arabic": "دَفَعَ", "pronunciation": "/peɪ/"},
            ],
            "sentences": [
                {"english": "I buy clothes from the shop.", "farsi": "من از فروشگاه لباس می‌خرم.",
                 "arabic": "أَشتَرِی مَلابِسَ مِنَ المَتجَرِ."},
                {"english": "The price of the shoes is high.", "farsi": "قیمت کفش‌ها بالاست.",
                 "arabic": "سِعرُ الجَزْمَةِ مُرتَفِعٌ."},
                {"english": "He sells bags in the market.", "farsi": "او در بازار کیف می‌فروشد.",
                 "arabic": "هُوَ یَبِیعُ حَقائِبَ فِی السُّوقِ."},
                {"english": "I need money to buy a new bag.", "farsi": "برای خرید کیف جدید به پول نیاز دارم.",
                 "arabic": "أَحتاجُ نُقوداً لِشِراءِ حَقِیبَةٍ جَدِیدَةٍ."},
                {"english": "The store has cheap clothes.", "farsi": "فروشگاه لباس‌های ارزان دارد.",
                 "arabic": "المَخزَنُ لَهُ مَلابِسُ رَخِیصَةٌ."},
                {"english": "This bag is expensive.", "farsi": "این کیف گران است.",
                 "arabic": "هٰذِهِ الحَقِیبَةُ غالِیَةٌ."},
                {"english": "We pay at the shop.", "farsi": "ما در فروشگاه پرداخت می‌کنیم.",
                 "arabic": "نَدفَعُ فِی المَتجَرِ."},
                {"english": "The market is near my house.", "farsi": "بازار نزدیک خانه من است.",
                 "arabic": "السُّوقُ قَرِیبٌ مِن بَیتِی."},
            ]
        },
        "lesson_5": {
            "words": [
                {"english": "Sport", "farsi": "ورزش", "arabic": "رِیاضَة", "pronunciation": "/spɔːrt/"},
                {"english": "Football", "farsi": "فوتبال", "arabic": "کُرَةُ القَدَم", "pronunciation": "/ˈfʊt.bɔːl/"},
                {"english": "Swimming", "farsi": "شنا", "arabic": "سِباحَة", "pronunciation": "/ˈswɪm.ɪŋ/"},
                {"english": "Running", "farsi": "دویدن", "arabic": "جَری", "pronunciation": "/ˈrʌn.ɪŋ/"},
                {"english": "Play", "farsi": "بازی کردن", "arabic": "لَعِبَ", "pronunciation": "/pleɪ/"},
                {"english": "Health", "farsi": "سلامتی", "arabic": "صِحَّة", "pronunciation": "/hɛlθ/"},
                {"english": "Exercise", "farsi": "تمرین", "arabic": "تَمرِین", "pronunciation": "/ˈɛk.sər.saɪz/"},
                {"english": "Team", "farsi": "تیم", "arabic": "فَرِیق", "pronunciation": "/tiːm/"},
                {"english": "Game", "farsi": "بازی", "arabic": "لُعبَة", "pronunciation": "/ɡeɪm/"},
                {"english": "Fitness", "farsi": "تناسب اندام", "arabic": "لِیاقَة", "pronunciation": "/ˈfɪt.nəs/"},
                {"english": "Gym", "farsi": "باشگاه", "arabic": "نادی رِیاضی", "pronunciation": "/dʒɪm/"},
                {"english": "Ball", "farsi": "توپ", "arabic": "کُرَة", "pronunciation": "/bɔːl/"},
                {"english": "Practice", "farsi": "تمرین کردن", "arabic": "تَدَرَّبَ", "pronunciation": "/ˈpræk.tɪs/"},
            ],
            "sentences": [
                {"english": "I like to play football with my team.", "farsi": "من دوست دارم با تیمم فوتبال بازی کنم.",
                 "arabic": "أُحِبُّ أَن أَلعَبَ کُرَةَ القَدَمِ مَعَ فَرِیقِی."},
                {"english": "Swimming is good for health.", "farsi": "شنا برای سلامتی خوب است.",
                 "arabic": "السِّباحَةُ جَیِّدَةٌ لِلصِّحَّةِ."},
                {"english": "Running keeps us fit.", "farsi": "دویدن ما را متناسب نگه می‌دارد.",
                 "arabic": "الجَری یُحافِظُ عَلَینا بِلِیاقَةٍ."},
                {"english": "We practice in the gym.", "farsi": "ما در باشگاه تمرین می‌کنیم.",
                 "arabic": "نَتَدَرَّبُ فِی النَّادی الرِّیاضی."},
                {"english": "The game is exciting.", "farsi": "بازی هیجان‌انگیز است.",
                 "arabic": "اللُّعبَةُ مُثِیرَةٌ."},
                {"english": "She plays with a ball.", "farsi": "او با توپ بازی می‌کند.",
                 "arabic": "هِیَ تَلعَبُ بِکُرَةٍ."},
                {"english": "Exercise is important for fitness.", "farsi": "تمرین برای تناسب اندام مهم است.",
                 "arabic": "التَّمرِینُ مُهِمٌّ لِلِّیاقَةِ."},
                {"english": "Our team wins the game.", "farsi": "تیم ما بازی را می‌برد.",
                 "arabic": "فَرِیقُنا یَفوزُ بِاللُّعبَةِ."},
            ]
        },
        "lesson_6": {
            "words": [
                {"english": "Travel", "farsi": "سفر", "arabic": "سَفَر", "pronunciation": "/ˈtræv.əl/"},
                {"english": "Bus", "farsi": "اتوبوس", "arabic": "حافِلَة", "pronunciation": "/bʌs/"},
                {"english": "Train", "farsi": "قطار", "arabic": "قِطار", "pronunciation": "/treɪn/"},
                {"english": "Airplane", "farsi": "هواپیما", "arabic": "طائِرَة", "pronunciation": "/ˈɛər.pleɪn/"},
                {"english": "Ticket", "farsi": "بلیط", "arabic": "تَذکِرَة", "pronunciation": "/ˈtɪk.ɪt/"},
                {"english": "Suitcase", "farsi": "چمدان", "arabic": "حَقِیبَةُ سَفَر", "pronunciation": "/ˈsuːt.keɪs/"},
                {"english": "City", "farsi": "شهر", "arabic": "مَدِینَة", "pronunciation": "/ˈsɪt.i/"},
                {"english": "Vacation", "farsi": "تعطیلات", "arabic": "إِجازَة", "pronunciation": "/vəˈkeɪ.ʃən/"},
                {"english": "Hotel", "farsi": "هتل", "arabic": "فُندُق", "pronunciation": "/hoʊˈtɛl/"},
                {"english": "Tourist", "farsi": "گردشگر", "arabic": "سائِح", "pronunciation": "/ˈtʊr.ɪst/"},
                {"english": "Trip", "farsi": "سفر کوتاه", "arabic": "رِحلَة", "pronunciation": "/trɪp/"},
                {"english": "Map", "farsi": "نقشه", "arabic": "خَرِیطَة", "pronunciation": "/mæp/"},
                {"english": "Journey", "farsi": "سفر طولانی", "arabic": "سَفَرٌ طَوِیل",
                 "pronunciation": "/ˈdʒɜːr.ni/"},
            ],
            "sentences": [
                {"english": "I travel by bus.", "farsi": "من با اتوبوس سفر می‌کنم.",
                 "arabic": "أَسافِرُ بِالحافِلَةِ."},
                {"english": "The train goes to the city.", "farsi": "قطار به شهر می‌رود.",
                 "arabic": "القِطارُ یَذهَبُ إلى المَدِینَةِ."},
                {"english": "We buy tickets for the airplane.", "farsi": "ما برای هواپیما بلیط می‌خریم.",
                 "arabic": "نَشتَرِی تَذاکِرَ لِلطّائِرَةِ."},
                {"english": "My suitcase is heavy.", "farsi": "چمدانم سنگین است.",
                 "arabic": "حَقِیبَةُ سَفَرِی ثَقِیلَةٌ."},
                {"english": "The hotel is nice.", "farsi": "هتل خوب است.", "arabic": "الفُندُقُ جَیِّدٌ."},
                {"english": "Tourists use a map.", "farsi": "گردشگران از نقشه استفاده می‌کنند.",
                 "arabic": "السُّیّاحُ یَستَخدِمونَ خَرِیطَةً."},
                {"english": "The trip was exciting.", "farsi": "سفر هیجان‌انگیز بود.",
                 "arabic": "الرِّحلَةُ کانَت مُثِیرَةً."},
                {"english": "Our journey takes two days.", "farsi": "سفر ما دو روز طول می‌کشد.",
                 "arabic": "سَفَرُنا یَستَغرِقُ یَومَینِ."},
            ]
        },
        "lesson_7": {
            "words": [
                {"english": "Computer", "farsi": "رایانه", "arabic": "حاسوب", "pronunciation": "/kəmˈpjuː.tər/"},
                {"english": "Phone", "farsi": "تلفن", "arabic": "هاتِف", "pronunciation": "/foʊn/"},
                {"english": "Internet", "farsi": "اینترنت", "arabic": "إنترنت", "pronunciation": "/ˈɪn.tər.net/"},
                {"english": "Email", "farsi": "ایمیل", "arabic": "بَرید إلِکترونِی", "pronunciation": "/ˈiː.meɪl/"},
                {"english": "Screen", "farsi": "صفحه نمایش", "arabic": "شاشَة", "pronunciation": "/skriːn/"},
                {"english": "Application", "farsi": "برنامه کاربردی", "arabic": "تَطبِیق",
                 "pronunciation": "/ˌæp.lɪˈkeɪ.ʃən/"},
                {"english": "Technology", "farsi": "فناوری", "arabic": "تِکنولوجِیا",
                 "pronunciation": "/tɛkˈnɒl.ə.dʒi/"},
                {"english": "Message", "farsi": "پیام", "arabic": "رِسالَة", "pronunciation": "/ˈmɛs.ɪdʒ/"},
                {"english": "Charger", "farsi": "شارژر", "arabic": "شاحِن", "pronunciation": "/ˈtʃɑːr.dʒər/"},
                {"english": "File", "farsi": "پرونده", "arabic": "مِلَف", "pronunciation": "/faɪl/"},
                {"english": "Download", "farsi": "دانلود کردن", "arabic": "تَنزِیل", "pronunciation": "/ˈdaʊn.loʊd/"},
                {"english": "Website", "farsi": "وب‌سایت", "arabic": "مَوقِع", "pronunciation": "/ˈwɛb.saɪt/"},
                {"english": "Use", "farsi": "استفاده کردن", "arabic": "اِستَخدَمَ", "pronunciation": "/juːz/"},
            ],
            "sentences": [
                {"english": "I use the computer every day.", "farsi": "من هر روز از رایانه استفاده می‌کنم.",
                 "arabic": "أَستَخدِمُ الحاسوبَ کُلَّ یَومٍ."},
                {"english": "She sends an email.", "farsi": "او یک ایمیل می‌فرستد.",
                 "arabic": "هِیَ تُرسِلُ بَریداً إلِکترونِیّاً."},
                {"english": "The phone is on the table.", "farsi": "تلفن روی میز است.",
                 "arabic": "الهاتِفُ عَلى المائِدَةِ."},
                {"english": "The internet is fast.", "farsi": "اینترنت سریع است.", "arabic": "الإنترنتُ سَرِیعٌ."},
                {"english": "I download files from the website.", "farsi": "من از وب‌سایت فایل دانلود می‌کنم.",
                 "arabic": "أُنَزِّلُ مَلَفّاتٍ مِنَ المَوقِعِ."},
                {"english": "The application is useful.", "farsi": "برنامه کاربردی مفید است.",
                 "arabic": "التَّطبِیقُ مُفِیدٌ."},
                {"english": "Technology helps us learn.", "farsi": "فناوری به ما کمک می‌کند یاد بگیریم.",
                 "arabic": "التِّکنولوجِیا تُساعِدُنا عَلى التَّعَلُّمِ."},
                {"english": "The charger is in my bag.", "farsi": "شارژر در کیف من است.",
                 "arabic": "الشّاحِنُ فِی حَقِیبَتِی."},
            ]
        },
        "lesson_8": {
            "words": [
                {"english": "Culture", "farsi": "فرهنگ", "arabic": "ثَقافَة", "pronunciation": "/ˈkʌl.tʃər/"},
                {"english": "Tradition", "farsi": "سنت", "arabic": "تَقلِید", "pronunciation": "/trəˈdɪʃ.ən/"},
                {"english": "Festival", "farsi": "جشن", "arabic": "عِید", "pronunciation": "/ˈfɛs.tɪ.vəl/"},
                {"english": "Food", "farsi": "غذا", "arabic": "طَعام", "pronunciation": "/fuːd/"},
                {"english": "Dance", "farsi": "رقص", "arabic": "رَقص", "pronunciation": "/dæns/"},
                {"english": "Music", "farsi": "موسیقی", "arabic": "موسِیقى", "pronunciation": "/ˈmjuː.zɪk/"},
                {"english": "Clothing", "farsi": "لباس", "arabic": "مَلابِس", "pronunciation": "/ˈkloʊ.ðɪŋ/"},
                {"english": "Celebration", "farsi": "جشن", "arabic": "اِحتِفال", "pronunciation": "/ˌsɛl.əˈbreɪ.ʃən/"},
                {"english": "Custom", "farsi": "رسم", "arabic": "عَادَة", "pronunciation": "/ˈkʌs.təm/"},
                {"english": "Art", "farsi": "هنر", "arabic": "فَن", "pronunciation": "/ɑːrt/"},
                {"english": "Family", "farsi": "خانواده", "arabic": "عائِلَة", "pronunciation": "/ˈfæm.əl.i/"},
                {"english": "Respect", "farsi": "احترام", "arabic": "اِحتِرام", "pronunciation": "/rɪˈspɛkt/"},
                {"english": "Tradition", "farsi": "سنت", "arabic": "تَقلِید", "pronunciation": "/trəˈdɪʃ.ən/"},
            ],
            "sentences": [
                {"english": "Our culture is rich.", "farsi": "فرهنگ ما غنی است.", "arabic": "ثَقافَتُنا غَنِیَّةٌ."},
                {"english": "We celebrate festivals with music.", "farsi": "ما جشن‌ها را با موسیقی برگزار می‌کنیم.",
                 "arabic": "نَحتَفِلُ بِالأَعيادِ بِالموسِیقى."},
                {"english": "Traditional food is delicious.", "farsi": "غذای سنتی خوشمزه است.",
                 "arabic": "الطَّعامُ التَّقلِیدِیُّ لَذِیذٌ."},
                {"english": "She wears traditional clothing.", "farsi": "او لباس سنتی می‌پوشد.",
                 "arabic": "هِیَ تَلبَسُ مَلابِسَ تَقلِیدِیَّةً."},
                {"english": "Dance is part of our customs.", "farsi": "رقص بخشی از رسوم ماست.",
                 "arabic": "الرَّقصُ جُزءٌ مِن عاداتِنا."},
                {"english": "We respect our family traditions.", "farsi": "ما به سنت‌های خانوادگی احترام می‌گذاریم.",
                 "arabic": "نَحتَرِمُ تَقالِیدَ عائِلَتِنا."},
                {"english": "Art shows our culture.", "farsi": "هنر فرهنگ ما را نشان می‌دهد.",
                 "arabic": "الفَنُّ یُظهِرُ ثَقافَتَنا."},
                {"english": "The celebration is big.", "farsi": "جشن بزرگ است.", "arabic": "الاِحتِفالُ کَبِیرٌ."},
            ]
        }
    },

    "9th_grade": {
        "lesson_1": {
            "words": [
                {"english": "Technology", "farsi": "فناوری", "arabic": "تِكنولوجِيا",
                 "pronunciation": "/tɛkˈnɒl.ə.dʒi/"},
                {"english": "Computer", "farsi": "رایانه", "arabic": "حاسوب", "pronunciation": "/kəmˈpjuː.tər/"},
                {"english": "Smartphone", "farsi": "گوشی هوشمند", "arabic": "هاتِف ذَكِي",
                 "pronunciation": "/ˈsmɑːrt.foʊn/"},
                {"english": "Internet", "farsi": "اینترنت", "arabic": "إنترنت", "pronunciation": "/ˈɪn.tər.net/"},
                {"english": "Email", "farsi": "ایمیل", "arabic": "بَريد إلِكترونِي", "pronunciation": "/ˈiː.meɪl/"},
                {"english": "Application", "farsi": "برنامه کاربردی", "arabic": "تَطبيق",
                 "pronunciation": "/ˌæp.lɪˈkeɪ.ʃən/"},
                {"english": "Software", "farsi": "نرم‌افزار", "arabic": "بَرمَجِيّات", "pronunciation": "/ˈsɒft.wɛər/"},
                {"english": "Device", "farsi": "دستگاه", "arabic": "جِهاز", "pronunciation": "/dɪˈvaɪs/"},
                {"english": "Network", "farsi": "شبکه", "arabic": "شَبَكَة", "pronunciation": "/ˈnet.wɜːrk/"},
                {"english": "Website", "farsi": "وب‌سایت", "arabic": "مَوقِع", "pronunciation": "/ˈwɛb.saɪt/"},
                {"english": "Download", "farsi": "دانلود کردن", "arabic": "تَنزيل", "pronunciation": "/ˈdaʊn.loʊd/"},
                {"english": "Update", "farsi": "به‌روزرسانی", "arabic": "تَحديث", "pronunciation": "/ˈʌp.deɪt/"},
                {"english": "Charger", "farsi": "شارژر", "arabic": "شاحِن", "pronunciation": "/ˈtʃɑːr.dʒər/"},
                {"english": "Message", "farsi": "پیام", "arabic": "رِسالَة", "pronunciation": "/ˈmɛs.ɪdʒ/"},
                {"english": "Connect", "farsi": "اتصال", "arabic": "اِتَّصَلَ", "pronunciation": "/kəˈnekt/"},
                {"english": "Innovation", "farsi": "نوآوری", "arabic": "اِبتِكار", "pronunciation": "/ˌɪn.əˈveɪ.ʃən/"},
            ],
            "sentences": [
                {"english": "Technology changes our lives.", "farsi": "فناوری زندگی ما را تغییر می‌دهد.",
                 "arabic": "التِّكنولوجِيا تُغَيِّرُ حَياتَنا."},
                {"english": "I use my smartphone every day.", "farsi": "من هر روز از گوشی هوشمندم استفاده می‌کنم.",
                 "arabic": "أَستَخدِمُ هاتِفِي الذَّكِي كُلَّ يَومٍ."},
                {"english": "The internet is very fast.", "farsi": "اینترنت بسیار سریع است.",
                 "arabic": "الإنترنتُ سَريعٌ جِدّاً."},
                {"english": "She sends an email to her friend.", "farsi": "او برای دوستش ایمیل می‌فرستد.",
                 "arabic": "هِيَ تُرسِلُ بَريداً إلِكترونِيّاً لِصَديقِها."},
                {"english": "This application is useful.", "farsi": "این برنامه کاربردی مفید است.",
                 "arabic": "هٰذا التَّطبيقُ مُفيدٌ."},
                {"english": "We need to update the software.", "farsi": "ما باید نرم‌افزار را به‌روزرسانی کنیم.",
                 "arabic": "نَحتاجُ إلى تَحديثِ البَرمَجِيّاتِ."},
                {"english": "My charger is in the bag.", "farsi": "شارژرم در کیف است.",
                 "arabic": "الشّاحِنُ فِي الحَقيبَةِ."},
                {"english": "The device connects to the network.", "farsi": "دستگاه به شبکه متصل می‌شود.",
                 "arabic": "الجِهازُ يَتَّصِلُ بِالشَّبَكَةِ."},
                {"english": "I download files from the website.", "farsi": "من از وب‌سایت فایل دانلود می‌کنم.",
                 "arabic": "أُنَزِّلُ مَلَفّاتٍ مِنَ المَوقِعِ."},
                {"english": "Innovation improves technology.", "farsi": "نوآوری فناوری را بهبود می‌بخشد.",
                 "arabic": "الاِبتِكارُ يُحَسِّنُ التِّكنولوجِيا."},
            ]
        },
        "lesson_2": {
            "words": [
                {"english": "Environment", "farsi": "محیط زیست", "arabic": "بيئَة",
                 "pronunciation": "/ɪnˈvaɪ.rən.mənt/"},
                {"english": "Nature", "farsi": "طبیعت", "arabic": "طَبيعَة", "pronunciation": "/ˈneɪ.tʃər/"},
                {"english": "Tree", "farsi": "درخت", "arabic": "شَجَرَة", "pronunciation": "/triː/"},
                {"english": "River", "farsi": "رودخانه", "arabic": "نَهر", "pronunciation": "/ˈrɪv.ər/"},
                {"english": "Mountain", "farsi": "کوه", "arabic": "جَبَل", "pronunciation": "/ˈmaʊn.tən/"},
                {"english": "Forest", "farsi": "جنگل", "arabic": "غابَة", "pronunciation": "/ˈfɔːr.ɪst/"},
                {"english": "Pollution", "farsi": "آلودگی", "arabic": "تَلَوُّث", "pronunciation": "/pəˈluː.ʃən/"},
                {"english": "Air", "farsi": "هوا", "arabic": "هَواء", "pronunciation": "/ɛər/"},
                {"english": "Water", "farsi": "آب", "arabic": "ماء", "pronunciation": "/ˈwɔː.tər/"},
                {"english": "Animal", "farsi": "حیوان", "arabic": "حَيَوان", "pronunciation": "/ˈæn.ɪ.məl/"},
                {"english": "Plant", "farsi": "گیاه", "arabic": "نَبات", "pronunciation": "/plænt/"},
                {"english": "Protect", "farsi": "محافظت کردن", "arabic": "حَمَى", "pronunciation": "/prəˈtɛkt/"},
                {"english": "Recycle", "farsi": "بازیافت", "arabic": "إِعادَة تَدوير",
                 "pronunciation": "/ˌriːˈsaɪ.kəl/"},
                {"english": "Clean", "farsi": "تمیز", "arabic": "نَظيف", "pronunciation": "/kliːn/"},
                {"english": "Awareness", "farsi": "آگاهی", "arabic": "تَوَعِيَة", "pronunciation": "/əˈwɛər.nəs/"},
                {"english": "Climate", "farsi": "اقلیم", "arabic": "مُناخ", "pronunciation": "/ˈklaɪ.mət/"},
            ],
            "sentences": [
                {"english": "We must protect the environment.", "farsi": "ما باید از محیط زیست محافظت کنیم.",
                 "arabic": "يَجِبُ أَن نَحمِيَ البيئَةَ."},
                {"english": "Nature is beautiful in the forest.", "farsi": "طبیعت در جنگل زیبا است.",
                 "arabic": "الطَّبيعَةُ جَميلَةٌ فِي الغابَةِ."},
                {"english": "The river is clean.", "farsi": "رودخانه تمیز است.", "arabic": "النَّهرُ نَظيفٌ."},
                {"english": "Pollution harms animals.", "farsi": "آلودگی به حیوانات آسیب می‌رساند.",
                 "arabic": "التَّلَوُّثُ يُؤذي الحَيَواناتِ."},
                {"english": "We plant trees every year.", "farsi": "ما هر سال درخت می‌کاریم.",
                 "arabic": "نَزرَعُ أَشجاراً كُلَّ عامٍ."},
                {"english": "Recycling helps the environment.", "farsi": "بازیافت به محیط زیست کمک می‌کند.",
                 "arabic": "إِعادَةُ التَّدويرِ تُساعِدُ البيئَةَ."},
                {"english": "The air is fresh in the mountains.", "farsi": "هوا در کوه‌ها تازه است.",
                 "arabic": "الهَواءُ نَقِيٌّ فِي الجِبالِ."},
                {"english": "Awareness about climate change is important.",
                 "farsi": "آگاهی درباره تغییرات اقلیمی مهم است.",
                 "arabic": "التَّوَعِيَةُ حَولَ تَغَيُّرِ المُناخِ مُهِمَّةٌ."},
                {"english": "Water is essential for plants.", "farsi": "آب برای گیاهان ضروری است.",
                 "arabic": "الماءُ أَساسِيٌّ لِلنَّباتاتِ."},
                {"english": "We need to clean our forests.", "farsi": "ما باید جنگل‌هایمان را تمیز کنیم.",
                 "arabic": "نَحتاجُ إلى تَنظيفِ غاباتِنا."},
            ]
        },
        "lesson_3": {
            "words": [
                {"english": "Culture", "farsi": "فرهنگ", "arabic": "ثَقافَة", "pronunciation": "/ˈkʌl.tʃər/"},
                {"english": "Tradition", "farsi": "سنت", "arabic": "تَقليد", "pronunciation": "/trəˈdɪʃ.ən/"},
                {"english": "Festival", "farsi": "جشن", "arabic": "عيد", "pronunciation": "/ˈfɛs.tɪ.vəl/"},
                {"english": "Heritage", "farsi": "میراث", "arabic": "تُراث", "pronunciation": "/ˈhɛr.ɪ.tɪdʒ/"},
                {"english": "Art", "farsi": "هنر", "arabic": "فَن", "pronunciation": "/ɑːrt/"},
                {"english": "Music", "farsi": "موسیقی", "arabic": "موسيقى", "pronunciation": "/ˈmjuː.zɪk/"},
                {"english": "Dance", "farsi": "رقص", "arabic": "رَقص", "pronunciation": "/dæns/"},
                {"english": "Clothing", "farsi": "لباس", "arabic": "مَلابِس", "pronunciation": "/ˈkloʊ.ðɪŋ/"},
                {"english": "Celebration", "farsi": "جشن", "arabic": "اِحتِفال", "pronunciation": "/ˌsɛl.əˈbreɪ.ʃən/"},
                {"english": "Custom", "farsi": "رسم", "arabic": "عادَة", "pronunciation": "/ˈkʌs.təm/"},
                {"english": "Museum", "farsi": "موزه", "arabic": "مَتحَف", "pronunciation": "/mjuˈziː.əm/"},
                {"english": "History", "farsi": "تاریخ", "arabic": "تاريخ", "pronunciation": "/ˈhɪs.tər.i/"},
                {"english": "Identity", "farsi": "هویت", "arabic": "هَوِيَّة", "pronunciation": "/aɪˈdɛn.tɪ.ti/"},
                {"english": "Respect", "farsi": "احترام", "arabic": "اِحتِرام", "pronunciation": "/rɪˈspɛkt/"},
                {"english": "Community", "farsi": "جامعه", "arabic": "مُجتَمَع", "pronunciation": "/kəˈmjuː.nə.ti/"},
                {"english": "Ceremony", "farsi": "مراسم", "arabic": "مَراسِم", "pronunciation": "/ˈsɛr.ɪ.mə.ni/"},
            ],
            "sentences": [
                {"english": "Our culture is very rich.", "farsi": "فرهنگ ما بسیار غنی است.",
                 "arabic": "ثَقافَتُنا غَنِيَّةٌ جِدّاً."},
                {"english": "We celebrate festivals with music and dance.",
                 "farsi": "ما جشن‌ها را با موسیقی و رقص برگزار می‌کنیم.",
                 "arabic": "نَحتَفِلُ بِالأَعيادِ بِالموسيقى وَالرَّقصِ."},
                {"english": "Traditional clothing is beautiful.", "farsi": "لباس سنتی زیبا است.",
                 "arabic": "المَلابِسُ التَّقليدِيَّةُ جَميلَةٌ."},
                {"english": "Heritage connects us to history.", "farsi": "میراث ما را به تاریخ متصل می‌کند.",
                 "arabic": "التُّراثُ يَصِلُنا بِالتاريخِ."},
                {"english": "The museum shows our art.", "farsi": "موزه هنر ما را نشان می‌دهد.",
                 "arabic": "المَتحَفُ يُظهِرُ فَنَّنا."},
                {"english": "Respect for customs is important.", "farsi": "احترام به رسوم مهم است.",
                 "arabic": "الاِحتِرامُ لِلعاداتِ مُهِمٌّ."},
                {"english": "The community enjoys the ceremony.", "farsi": "جامعه از مراسم لذت می‌برد.",
                 "arabic": "المُجتَمَعُ يَستَمتِعُ بِالمَراسِمِ."},
                {"english": "Our identity comes from our culture.", "farsi": "هویت ما از فرهنگمان می‌آید.",
                 "arabic": "هَوِيَّتُنا تَأتي مِن ثَقافَتِنا."},
                {"english": "Art and music are part of our traditions.",
                 "farsi": "هنر و موسیقی بخشی از سنت‌های ما هستند.",
                 "arabic": "الفَنُّ وَالموسيقى جُزءٌ مِن تَقاليدِنا."},
                {"english": "The festival is a big celebration.", "farsi": "جشن یک مراسم بزرگ است.",
                 "arabic": "العيدُ اِحتِفالٌ كَبيرٌ."},
            ]
        },
        "lesson_4": {
            "words": [
                {"english": "Hobby", "farsi": "سرگرمی", "arabic": "هِوايَة", "pronunciation": "/ˈhɒb.i/"},
                {"english": "Reading", "farsi": "خواندن", "arabic": "قِراءَة", "pronunciation": "/ˈriː.dɪŋ/"},
                {"english": "Drawing", "farsi": "نقاشی", "arabic": "رَسم", "pronunciation": "/ˈdrɔː.ɪŋ/"},
                {"english": "Photography", "farsi": "عکاسی", "arabic": "تَصوير", "pronunciation": "/fəˈtɒɡ.rə.fi/"},
                {"english": "Sport", "farsi": "ورزش", "arabic": "رِياضَة", "pronunciation": "/spɔːrt/"},
                {"english": "Music", "farsi": "موسیقی", "arabic": "موسيقى", "pronunciation": "/ˈmjuː.zɪk/"},
                {"english": "Traveling", "farsi": "سفر کردن", "arabic": "سَفَر", "pronunciation": "/ˈtræv.əl.ɪŋ/"},
                {"english": "Game", "farsi": "بازی", "arabic": "لُعبَة", "pronunciation": "/ɡeɪm/"},
                {"english": "Movie", "farsi": "فیلم", "arabic": "فيلم", "pronunciation": "/ˈmuː.vi/"},
                {"english": "Camping", "farsi": "کمپینگ", "arabic": "تَخييم", "pronunciation": "/ˈkæmp.ɪŋ/"},
                {"english": "Hiking", "farsi": "کوهنوردی", "arabic": "تَسلُّق", "pronunciation": "/ˈhaɪ.kɪŋ/"},
                {"english": "Leisure", "farsi": "اوقات فراغت", "arabic": "فَراغ", "pronunciation": "/ˈliː.ʒər/"},
                {"english": "Relax", "farsi": "آرامش کردن", "arabic": "اِستَرخَى", "pronunciation": "/rɪˈlæks/"},
                {"english": "Activity", "farsi": "فعالیت", "arabic": "نَشاط", "pronunciation": "/ækˈtɪv.ɪ.ti/"},
                {"english": "Interest", "farsi": "علاقه", "arabic": "اِهتِمام", "pronunciation": "/ˈɪn.tər.ɪst/"},
                {"english": "Fun", "farsi": "سرگرمی", "arabic": "مُتْعَة", "pronunciation": "/fʌn/"},
            ],
            "sentences": [
                {"english": "Reading is my favorite hobby.", "farsi": "خواندن سرگرمی مورد علاقه من است.",
                 "arabic": "القِراءَةُ هِوايَتي المُفَضَّلَةُ."},
                {"english": "I enjoy drawing in my leisure time.", "farsi": "من از نقاشی در اوقات فراغتم لذت می‌برم.",
                 "arabic": "أَستَمتِعُ بِالرَّسمِ فِي فَراغي."},
                {"english": "Photography is a fun activity.", "farsi": "عکاسی یک فعالیت سرگرم‌کننده است.",
                 "arabic": "التَّصويرُ نَشاطٌ مُمْتِعٌ."},
                {"english": "We go camping every summer.", "farsi": "ما هر تابستان به کمپینگ می‌رویم.",
                 "arabic": "نَذهَبُ لِلتَّخييمِ كُلَّ صَيفٍ."},
                {"english": "Traveling is an interesting hobby.", "farsi": "سفر کردن یک سرگرمی جالب است.",
                 "arabic": "السَّفَرُ هِوايَةٌ مُثيرَةٌ."},
                {"english": "Playing sports helps me relax.", "farsi": "بازی کردن ورزش به من کمک می‌کند آرامش کنم.",
                 "arabic": "لَعبُ الرِّياضَةِ يُساعِدُني عَلى الاِستِرخاءِ."},
                {"english": "I watch movies for fun.", "farsi": "من برای سرگرمی فیلم تماشا می‌کنم.",
                 "arabic": "أُشاهِدُ الأَفلامَ لِلمُتْعَةِ."},
                {"english": "Hiking in the mountains is exciting.", "farsi": "کوهنوردی در کوه‌ها هیجان‌انگیز است.",
                 "arabic": "التَّسلُّقُ فِي الجِبالِ مُثيرٌ."},
                {"english": "Music is a popular leisure activity.", "farsi": "موسیقی یک فعالیت اوقات فراغت محبوب است.",
                 "arabic": "الموسيقى نَشاطٌ فَراغٍ شَعبِيٌّ."},
                {"english": "My interests include games and drawing.",
                 "farsi": "علاقه‌های من شامل بازی‌ها و نقاشی است.",
                 "arabic": "اِهتِماماتي تَشمَلُ الأَلعابَ وَالرَّسمَ."},
            ]
        },
        "lesson_5": {
            "words": [
                {"english": "History", "farsi": "تاریخ", "arabic": "تاريخ", "pronunciation": "/ˈhɪs.tər.i/"},
                {"english": "Geography", "farsi": "جغرافیا", "arabic": "جُغرافيا", "pronunciation": "/dʒiˈɒɡ.rə.fi/"},
                {"english": "City", "farsi": "شهر", "arabic": "مَدينَة", "pronunciation": "/ˈsɪt.i/"},
                {"english": "Country", "farsi": "کشور", "arabic": "بَلَد", "pronunciation": "/ˈkʌn.tri/"},
                {"english": "Capital", "farsi": "پایتخت", "arabic": "عاصِمَة", "pronunciation": "/ˈkæp.ɪ.təl/"},
                {"english": "Continent", "farsi": "قاره", "arabic": "قارَّة", "pronunciation": "/ˈkɒn.tɪ.nənt/"},
                {"english": "Civilization", "farsi": "تمدن", "arabic": "حَضارَة",
                 "pronunciation": "/ˌsɪv.əl.əˈzeɪ.ʃən/"},
                {"english": "Kingdom", "farsi": "پادشاهی", "arabic": "مَملَكَة", "pronunciation": "/ˈkɪŋ.dəm/"},
                {"english": "War", "farsi": "جنگ", "arabic": "حَرب", "pronunciation": "/wɔːr/"},
                {"english": "Peace", "farsi": "صلح", "arabic": "سَلام", "pronunciation": "/piːs/"},
                {"english": "King", "farsi": "پادشاه", "arabic": "مَلِك", "pronunciation": "/kɪŋ/"},
                {"english": "Map", "farsi": "نقشه", "arabic": "خَريطَة", "pronunciation": "/mæp/"},
                {"english": "Border", "farsi": "مرز", "arabic": "حُدود", "pronunciation": "/ˈbɔːr.dər/"},
                {"english": "Population", "farsi": "جمعیت", "arabic": "سُكّان", "pronunciation": "/ˌpɒp.jəˈleɪ.ʃən/"},
                {"english": "Era", "farsi": "عصر", "arabic": "عَصر", "pronunciation": "/ˈɪr.ə/"},
                {"english": "Ancient", "farsi": "باستانی", "arabic": "قَديم", "pronunciation": "/ˈeɪn.ʃənt/"},
            ],
            "sentences": [
                {"english": "History teaches us about the past.", "farsi": "تاریخ درباره گذشته به ما می‌آموزد.",
                 "arabic": "التاريخُ يُعَلِّمُنا عَنِ الماضي."},
                {"english": "Geography shows us the world.", "farsi": "جغرافیا جهان را به ما نشان می‌دهد.",
                 "arabic": "الجُغرافيا تُرينا العالَمَ."},
                {"english": "The capital of the country is big.", "farsi": "پایتخت کشور بزرگ است.",
                 "arabic": "عاصِمَةُ البَلَدِ كَبيرَةٌ."},
                {"english": "Ancient civilizations are interesting.", "farsi": "تمدن‌های باستانی جالب هستند.",
                 "arabic": "الحَضاراتُ القَديمَةُ مُثيرَةٌ."},
                {"english": "The king ruled the kingdom.", "farsi": "پادشاه بر پادشاهی حکومت کرد.",
                 "arabic": "المَلِكُ حَكَمَ المَملَكَةَ."},
                {"english": "Peace is better than war.", "farsi": "صلح بهتر از جنگ است.",
                 "arabic": "السَّلامُ أَفضَلُ مِنَ الحَربِ."},
                {"english": "I study the map of the continent.", "farsi": "من نقشه قاره را مطالعه می‌کنم.",
                 "arabic": "أَدرُسُ خَريطَةَ القارَّةِ."},
                {"english": "The population lives near the border.", "farsi": "جمعیت نزدیک مرز زندگی می‌کند.",
                 "arabic": "السُّكّانُ يَعيشونَ بِجِوارِ الحُدودِ."},
                {"english": "This era was important in history.", "farsi": "این عصر در تاریخ مهم بود.",
                 "arabic": "هٰذا العَصرُ كانَ مُهِمّاً فِي التاريخِ."},
                {"english": "The city has a rich history.", "farsi": "شهر تاریخ غنی دارد.",
                 "arabic": "المَدينَةُ لَها تاريخٌ غَنِيٌّ."},
            ]
        },
        "lesson_6": {
            "words": [
                {"english": "Religion", "farsi": "دین", "arabic": "دين", "pronunciation": "/rɪˈlɪdʒ.ən/"},
                {"english": "Faith", "farsi": "ایمان", "arabic": "إيمان", "pronunciation": "/feɪθ/"},
                {"english": "Prayer", "farsi": "نماز", "arabic": "صَلاة", "pronunciation": "/prɛər/"},
                {"english": "Fasting", "farsi": "روزه", "arabic": "صَوم", "pronunciation": "/ˈfæs.tɪŋ/"},
                {"english": "Charity", "farsi": "صدقه", "arabic": "صَدَقَة", "pronunciation": "/ˈtʃær.ɪ.ti/"},
                {"english": "Pilgrimage", "farsi": "زیارت", "arabic": "حَجّ", "pronunciation": "/ˈpɪl.ɡrɪ.mɪdʒ/"},
                {"english": "Mosque", "farsi": "مسجد", "arabic": "مَسجِد", "pronunciation": "/mɒsk/"},
                {"english": "Book", "farsi": "کتاب", "arabic": "كِتاب", "pronunciation": "/bʊk/"},
                {"english": "Values", "farsi": "ارزش‌ها", "arabic": "قِيَم", "pronunciation": "/ˈvæl.juːz/"},
                {"english": "Morals", "farsi": "اخلاق", "arabic": "أَخلاق", "pronunciation": "/ˈmɔːr.əlz/"},
                {"english": "Respect", "farsi": "احترام", "arabic": "اِحتِرام", "pronunciation": "/rɪˈspɛkt/"},
                {"english": "Kindness", "farsi": "مهربانی", "arabic": "لُطف", "pronunciation": "/ˈkaɪnd.nəs/"},
                {"english": "Worship", "farsi": "عبادت", "arabic": "تَعبُّد", "pronunciation": "/ˈwɜːr.ʃɪp/"},
                {"english": "Peace", "farsi": "صلح", "arabic": "سَلام", "pronunciation": "/piːs/"},
                {"english": "Community", "farsi": "جامعه", "arabic": "مُجتَمَع", "pronunciation": "/kəˈmjuː.nə.ti/"},
            ],
            "sentences": [
                {"english": "Religion teaches us values.", "farsi": "دین به ما ارزش‌ها می‌آموزد.",
                 "arabic": "الدّينُ يُعَلِّمُنا القِيَمَ."},
                {"english": "Faith gives us hope.", "farsi": "ایمان به ما امید می‌دهد.",
                 "arabic": "الإيمانُ يُعطينا الأَمَلَ."},
                {"english": "I pray in the mosque.", "farsi": "من در مسجد نماز می‌خوانم.",
                 "arabic": "أُصَلّي فِي المَسجِدِ."},
                {"english": "Fasting is important in our religion.", "farsi": "روزه در دین ما مهم است.",
                 "arabic": "الصَّومُ مُهِمٌّ فِي دينِنا."},
                {"english": "Charity helps the poor.", "farsi": "صدقه به فقرا کمک می‌کند.",
                 "arabic": "الصَّدَقَةُ تُساعِدُ الفُقَراءَ."},
                {"english": "Pilgrimage is a spiritual journey.", "farsi": "زیارت یک سفر معنوی است.",
                 "arabic": "الحَجُّ رِحلَةٌ رُوحِيَّةٌ."},
                {"english": "We read holy books for guidance.", "farsi": "ما برای هدایت کتاب‌های مقدس را می‌خوانیم.",
                 "arabic": "نَقرَأُ كُتُباً مُقَدَّسَةً لِلرِّشادِ."},
                {"english": "Kindness and respect are important morals.",
                 "farsi": "مهربانی و احترام ارزش‌های اخلاقی مهمی هستند.",
                 "arabic": "اللُّطفُ وَالاِحتِرامُ قِيَمٌ أَخلاقِيَّةٌ مُهِمَّةٌ."},
                {"english": "The community gathers for worship.", "farsi": "جامعه برای عبادت جمع می‌شود.",
                 "arabic": "المُجتَمَعُ يَتَجَمَّعُ لِلتَّعبُّدِ."},
                {"english": "Peace is a religious value.", "farsi": "صلح یک ارزش دینی است.",
                 "arabic": "السَّلامُ قيمَةٌ دينِيَّةٌ."},
            ]
        },
        "lesson_7": {
            "words": [
                {"english": "Conversation", "farsi": "مکالمه", "arabic": "مُحادَثَة",
                 "pronunciation": "/ˌkɒn.vərˈseɪ.ʃən/"},
                {"english": "Question", "farsi": "سوال", "arabic": "سُؤال", "pronunciation": "/ˈkwɛs.tʃən/"},
                {"english": "Answer", "farsi": "جواب", "arabic": "جَواب", "pronunciation": "/ˈæn.sər/"},
                {"english": "Discussion", "farsi": "بحث", "arabic": "نِقاش", "pronunciation": "/dɪˈskʌʃ.ən/"},
                {"english": "Opinion", "farsi": "نظر", "arabic": "رَأي", "pronunciation": "/əˈpɪn.jən/"},
                {"english": "Agreement", "farsi": "توافق", "arabic": "اِتِّفاق", "pronunciation": "/əˈɡriː.mənt/"},
                {"english": "Disagreement", "farsi": "اختلاف", "arabic": "اِختِلاف",
                 "pronunciation": "/ˌdɪs.əˈɡriː.mənt/"},
                {"english": "Friend", "farsi": "دوست", "arabic": "صَديق", "pronunciation": "/frɛnd/"},
                {"english": "Meeting", "farsi": "ملاقات", "arabic": "لِقاء", "pronunciation": "/ˈmiː.tɪŋ/"},
                {"english": "Communication", "farsi": "ارتباط", "arabic": "تَواصُل",
                 "pronunciation": "/kəˌmjuː.nɪˈkeɪ.ʃən/"},
                {"english": "Topic", "farsi": "موضوع", "arabic": "مَوضوع", "pronunciation": "/ˈtɒp.ɪk/"},
                {"english": "Talk", "farsi": "صحبت کردن", "arabic": "تَحَدَّثَ", "pronunciation": "/tɔːk/"},
                {"english": "Listen", "farsi": "گوش دادن", "arabic": "اِستَمَعَ", "pronunciation": "/ˈlɪs.ən/"},
                {"english": "Share", "farsi": "به اشتراک گذاشتن", "arabic": "شارَكَ", "pronunciation": "/ʃɛər/"},
                {"english": "Respect", "farsi": "احترام", "arabic": "اِحتِرام", "pronunciation": "/rɪˈspɛkt/"},
            ],
            "sentences": [
                {"english": "I have a conversation with my friend.", "farsi": "من با دوستم مکالمه می‌کنم.",
                 "arabic": "أُحادِثُ صَديقي."},
                {"english": "She asks an interesting question.", "farsi": "او یک سوال جالب می‌پرسد.",
                 "arabic": "هِيَ تَسأَلُ سُؤالاً مُثيراً."},
                {"english": "The answer is clear.", "farsi": "جواب واضح است.", "arabic": "الجَوابُ واضِحٌ."},
                {"english": "We have a discussion about the topic.", "farsi": "ما درباره موضوع بحث می‌کنیم.",
                 "arabic": "نَتَناقَشُ حَولَ المَوضوعِ."},
                {"english": "My opinion is different.", "farsi": "نظرم متفاوت است.", "arabic": "رَأيي مُختَلِفٌ."},
                {"english": "We reach an agreement.", "farsi": "ما به توافق می‌رسیم.",
                 "arabic": "نَصِلُ إلى اِتِّفاقٍ."},
                {"english": "Disagreement is normal in discussions.", "farsi": "اختلاف در بحث‌ها عادی است.",
                 "arabic": "الاِختِلافُ طَبيعِيٌّ فِي النِّقاشاتِ."},
                {"english": "I listen to my friend carefully.", "farsi": "من به دوستم با دقت گوش می‌دهم.",
                 "arabic": "أَستَمِعُ إلى صَديقي بِعِنايَةٍ."},
                {"english": "We share our ideas in the meeting.",
                 "farsi": "ما ایده‌هایمان را در ملاقات به اشتراک می‌گذاریم.",
                 "arabic": "نُشارِكُ أَفكارَنا فِي اللِّقاءِ."},
                {"english": "Respect is important in communication.", "farsi": "احترام در ارتباط مهم است.",
                 "arabic": "الاِحتِرامُ مُهِمٌّ فِي التَّواصُلِ."},
            ]
        },
        "lesson_8": {
            "words": [
                {"english": "Health", "farsi": "سلامتی", "arabic": "صِحَّة", "pronunciation": "/hɛlθ/"},
                {"english": "Exercise", "farsi": "ورزش", "arabic": "تَمرين", "pronunciation": "/ˈɛk.sər.saɪz/"},
                {"english": "Diet", "farsi": "رژیم غذایی", "arabic": "نِظام غِذائِي", "pronunciation": "/ˈdaɪ.ət/"},
                {"english": "Food", "farsi": "غذا", "arabic": "طَعام", "pronunciation": "/fuːd/"},
                {"english": "Sleep", "farsi": "خواب", "arabic": "نَوم", "pronunciation": "/sliːp/"},
                {"english": "Doctor", "farsi": "پزشک", "arabic": "طَبيب", "pronunciation": "/ˈdɒk.tər/"},
                {"english": "Hospital", "farsi": "بیمارستان", "arabic": "مُستَشفى", "pronunciation": "/ˈhɒs.pɪ.təl/"},
                {"english": "Medicine", "farsi": "دارو", "arabic": "دَواء", "pronunciation": "/ˈmɛd.ɪ.sən/"},
                {"english": "Fitness", "farsi": "تناسب اندام", "arabic": "لِياقَة", "pronunciation": "/ˈfɪt.nəs/"},
                {"english": "Energy", "farsi": "انرژی", "arabic": "طاقَة", "pronunciation": "/ˈɛn.ər.dʒi/"},
                {"english": "Balance", "farsi": "تعادل", "arabic": "تَوازُن", "pronunciation": "/ˈbæl.əns/"},
                {"english": "Lifestyle", "farsi": "سبک زندگی", "arabic": "أُسلوب حَياة",
                 "pronunciation": "/ˈlaɪf.staɪl/"},
                {"english": "Stress", "farsi": "استرس", "arabic": "ضَغط", "pronunciation": "/strɛs/"},
                {"english": "Healthy", "farsi": "سالم", "arabic": "صَحيح", "pronunciation": "/ˈhɛl.θi/"},
                {"english": "Care", "farsi": "مراقبت", "arabic": "رِعايَة", "pronunciation": "/kɛər/"},
                {"english": "Nutrition", "farsi": "تغذیه", "arabic": "تَغذِيَة", "pronunciation": "/njuˈtrɪʃ.ən/"},
            ],
            "sentences": [
                {"english": "Health is very important.", "farsi": "سلامتی بسیار مهم است.",
                 "arabic": "الصِّحَّةُ مُهِمَّةٌ جِدّاً."},
                {"english": "Exercise keeps us healthy.", "farsi": "ورزش ما را سالم نگه می‌دارد.",
                 "arabic": "التَّمرينُ يُحافِظُ عَلَينا صَحيحينَ."},
                {"english": "A good diet gives us energy.", "farsi": "رژیم غذایی خوب به ما انرژی می‌دهد.",
                 "arabic": "نِظامٌ غِذائِيٌّ جَيِّدٌ يُعطينا طاقَةً."},
                {"english": "I sleep eight hours every night.", "farsi": "من هر شب هشت ساعت می‌خوابم.",
                 "arabic": "أَنامُ ثَمانِيَ ساعاتٍ كُلَّ لَيلَةٍ."},
                {"english": "The doctor works in the hospital.", "farsi": "پزشک در بیمارستان کار می‌کند.",
                 "arabic": "الطَّبيبُ يَعمَلُ فِي المُستَشفى."},
                {"english": "Medicine helps us feel better.", "farsi": "دارو به ما کمک می‌کند احساس بهتری داشته باشیم.",
                 "arabic": "الدَّواءُ يُساعِدُنا عَلى الشُّعورِ بِالرَّاحَةِ."},
                {"english": "A healthy lifestyle reduces stress.", "farsi": "سبک زندگی سالم استرس را کاهش می‌دهد.",
                 "arabic": "أُسلوبُ حَياةٍ صَحيحٌ يُقَلِّلُ الضَّغطَ."},
                {"english": "Nutrition is key to fitness.", "farsi": "تغذیه کلید تناسب اندام است.",
                 "arabic": "التَّغذِيَةُ هِيَ مِفتاحُ اللِّياقَةِ."},
                {"english": "We need balance in our lives.", "farsi": "ما به تعادل در زندگی‌مان نیاز داریم.",
                 "arabic": "نَحتاجُ إلى تَوازُنٍ فِي حَياتِنا."},
                {"english": "Care for your health every day.", "farsi": "هر روز از سلامتی‌ات مراقبت کن.",
                 "arabic": "اِهتَمَّ بِصِحَّتِكَ كُلَّ يَومٍ."},
            ]
        }
    }

}
